import { MIExportTestResult } from '../../domain/mi-export-data';

// TODO: Oracle client initialisation...

/**
 * Saves a test result to the RSIS MI DB, by populating a staging table.
 * @param testResult The test result to save
 */
export const saveTestResult = (testResult: MIExportTestResult) => {
  // TODO: real SQL call
  // example with column mapping...
  // tslint:disable-next-line:prefer-template
  const insertStatement = `
    insert into dl25_holding (` +
    // TODO: add channel indicator
    //  REC_TYPE,
    //  REC_NO,
    //  FORM_TYPE,
    `
      DRIVING_SCHOOL_CANDIDATE,
      SPECIAL_NEEDS,
      APP_REF_NO,
      DRIVER_NO_DOB,
      DATE_OF_TEST,
      TIME,
      DTC_AUTHORITY_CODE,
      STAFF_NO,
      TEST_CATEGORY_TYPE,
      AUTOMATIC_TEST,
      EXTENDED_TEST,
      TEST_TYPE,
      ADI_NUMBER,` +
    // ADI_REF_CODE
    `
      ACCOMPANIED_BY_DSA,
      ACCOMPANIED_BY_ADI,
      ACCOMPANIED_BY_INTERPRETER,
      ACCOMPANIED_BY_OTHER,
      VISITING_EXAMINER,
      SHORT_NOTICE_EXAMINER,` +
/*
 EYESIGHT_SERIOUS                                   NUMBER(1)
 H_CODE_SAFETY_TOTAL                                NUMBER(2)
 CONTROL_STOP_PROMPT_TOTAL                          NUMBER(2)
 CONTROL_STOP_CONTROL_TOTAL                         NUMBER(2)
 REV_LEFT_TRAIL_CONT_TOTAL                          NUMBER(2)
 REV_LEFT_TRAIL_OBSERV_TOTAL                        NUMBER(2)
 REV_RIGHT_TRAIL_CONT_TOTAL                         NUMBER(2)
 REV_RIGHT_TRAIL_OBSERV_TOTAL                       NUMBER(2)
 REVERSE_PARK_CONT_TOTAL                            NUMBER(2)
 REVERSE_PARK_OBSERV_TOTAL                          NUMBER(2)
 TURN_IN_ROAD_CONT_TOTAL                            NUMBER(2)
 TURN_IN_ROAD_OBSERV_TOTAL                          NUMBER(2)
 VEHICLE_CHECKS_TOTAL                               NUMBER(2)
 TAXI_MAN_CONTROL_TOTAL                             NUMBER(2)
 TAXI_MAN_OBSERV_TOTAL                              NUMBER(2)
 TAXI_WHEELCHAIR_TOTAL                              NUMBER(2)
 UNCOUPLE_RECOUPLE_TOTAL                            NUMBER(2)
 PRECAUTIONS_TOTAL                                  NUMBER(2)
 CONTROL_ACC_TOTAL                                  NUMBER(2)
 CONTROL_CLUTCH_TOTAL                               NUMBER(2)
 CONTROL_GEARS_TOTAL                                NUMBER(2)
 CONTROL_FOOTBRAKE_TOTAL                            NUMBER(2)
 CONTROL_PARK_TOTAL                                 NUMBER(2)
 CONTROL_STEERING_TOTAL                             NUMBER(2)
 CONTROL_BALANCE_TOTAL                              NUMBER(2)
 CONTROL_LGV_PCV_GEAR_TOTAL                         NUMBER(2)
 CONTROL_PCV_DOOR_TOTAL                             NUMBER(2)
 MOVE_OFF_SAFETY_TOTAL                              NUMBER(2)
 MOVE_OFF_CONTROL_TOTAL                             NUMBER(2)
 MIRRORS_MC_REAR_SIG_TOTAL                          NUMBER(2)
 MIRRORS_MC_REAR_DIR_TOTAL                          NUMBER(2)
 MIRRORS_MC_REAR_SPE_TOTAL                          NUMBER(2)
 SIGNALS_NECESSARY_TOTAL                            NUMBER(2)
 SIGNALS_CORRECTLY_TOTAL                            NUMBER(2)
 SIGNALS_TIMED_TOTAL                                NUMBER(2)
 CLEARANCE_OBSTRUCT_TOTAL                           NUMBER(2)
 RESPONSE_TRAF_SIGNS_TOTAL                          NUMBER(2)
 RESPONSE_ROAD_MARK_TOTAL                           NUMBER(2)
 RESPONSE_TRAF_LIGHT_TOTAL                          NUMBER(2)
 RESPONSE_TRAF_CONT_TOTAL                           NUMBER(2)
 RESPONSE_OTHER_TOTAL                               NUMBER(2)
 USE_OF_SPEED_TOTAL                                 NUMBER(2)
 FOLLOWING_DISTANCE_TOTAL                           NUMBER(2)
 MAINTAIN_PROG_SPEED_TOTAL                          NUMBER(2)
 MAINTAIN_PROG_HES_TOTAL                            NUMBER(2)
 JUNCTIONS_SPEED_TOTAL                              NUMBER(2)
 JUNCTIONS_OBSERV_TOTAL                             NUMBER(2)
 JUNCTIONS_TURN_RIGHT_TOTAL                         NUMBER(2)
 JUNCTIONS_TURN_LEFT_TOTAL                          NUMBER(2)
 JUNCTIONS_TURN_CUT_TOTAL                           NUMBER(2)
 JUDGEMENT_OVER_TOTAL                               NUMBER(2)
 JUDGEMENT_MEET_TOTAL                               NUMBER(2)
 JUDGEMENT_CROSS_TOTAL                              NUMBER(2)
 POSITIONING_NORMAL_TOTAL                           NUMBER(2)
 POSITIONING_LANE_TOTAL                             NUMBER(2)
 PEDESTRIAN_CROSSING_TOTAL                          NUMBER(2)
 POSTITION_STOPS_TOTAL                              NUMBER(2)
 AWARENESS_PLAN_TOTAL                               NUMBER(2)
 ANCILLARY_CONTROLS_TOTAL                           NUMBER(2)
 SPARE1_TOTAL                                       NUMBER(2)
 SPARE2_TOTAL                                       NUMBER(2)
 SPARE3_TOTAL                                       NUMBER(2)
 SPARE4_TOTAL                                       NUMBER(2)
 SPARE5_TOTAL                                       NUMBER(2)
 H_CODE_SAFETY_SERIOUS                              NUMBER(1)
 CONTROL_STOP_PROMPT_SERIOUS                        NUMBER(1)
 CONTROL_STOP_CONTROL_SERIOUS                       NUMBER(1)
 REV_LEFT_TRAIL_CONT_SERIOUS                        NUMBER(1)
 REV_LEFT_TRAIL_OBSERV_SERIOUS                      NUMBER(1)
 REV_RIGHT_TRAIL_CONT_SERIOUS                       NUMBER(1)
 REV_RIGHT_TRAIL_OBSERV_SERIOUS                     NUMBER(1)
 REVERSE_PARK_CONT_SERIOUS                          NUMBER(1)
 REVERSE_PARK_OBSERV_SERIOUS                        NUMBER(1)
 TURN_IN_ROAD_CONT_SERIOUS                          NUMBER(1)
 TURN_IN_ROAD_OBSERV_SERIOUS                        NUMBER(1)
 VEHICLE_CHECKS_SERIOUS                             NUMBER(1)
 TAXI_MAN_CONTROL_SERIOUS                           NUMBER(1)
 TAXI_MAN_OBSERV_SERIOUS                            NUMBER(1)
 TAXI_WHEELCHAIR_SERIOUS                            NUMBER(1)
 UNCOUPLE_RECOUPLE_SERIOUS                          NUMBER(1)
 PRECAUTIONS_SERIOUS                                NUMBER(1)
 CONTROL_ACC_SERIOUS                                NUMBER(1)
 CONTROL_CLUTCH_SERIOUS                             NUMBER(1)
 CONTROL_GEARS_SERIOUS                              NUMBER(1)
 CONTROL_FOOTBRAKE_SERIOUS                          NUMBER(1)
 CONTROL_PARK_SERIOUS                               NUMBER(1)
 CONTROL_STEERING_SERIOUS                           NUMBER(1)
 CONTROL_BALANCE_SERIOUS                            NUMBER(1)
 CONTROL_LGV_PCV_GEAR_SERIOUS                       NUMBER(1)
 CONTROL_PCV_DOOR_SERIOUS                           NUMBER(1)
 MOVE_OFF_SAFETY_SERIOUS                            NUMBER(1)
 MOVE_OFF_CONTROL_SERIOUS                           NUMBER(1)
 MIRRORS_MC_REAR_SIG_SERIOUS                        NUMBER(1)
 MIRRORS_MC_REAR_DIR_SERIOUS                        NUMBER(1)
 MIRRORS_MC_REAR_SPE_SERIOUS                        NUMBER(1)
 SIGNALS_NECESSARY_SERIOUS                          NUMBER(1)
 SIGNALS_CORRECTLY_SERIOUS                          NUMBER(1)
 SIGNALS_TIMED_SERIOUS                              NUMBER(1)
 CLEARANCE_OBSTRUCT_SERIOUS                         NUMBER(1)
 RESPONSE_TRAF_SIGNS_SERIOUS                        NUMBER(1)
 RESPONSE_ROAD_MARK_SERIOUS                         NUMBER(1)
 RESPONSE_TRAF_LIGHT_SERIOUS                        NUMBER(1)
 RESPONSE_TRAF_CONT_SERIOUS                         NUMBER(1)
 RESPONSE_OTHER_SERIOUS                             NUMBER(1)
 USE_OF_SPEED_SERIOUS                               NUMBER(1)
 FOLLOWING_DISTANCE_SERIOUS                         NUMBER(1)
 MAINTAIN_PROG_SPEED_SERIOUS                        NUMBER(1)
 MAINTAIN_PROG_HES_SERIOUS                          NUMBER(1)
 JUNCTIONS_SPEED_SERIOUS                            NUMBER(1)
 JUNCTIONS_OBSERV_SERIOUS                           NUMBER(1)
 JUNCTIONS_TURN_RIGHT_SERIOUS                       NUMBER(1)
 JUNCTIONS_TURN_LEFT_SERIOUS                        NUMBER(1)
 JUNCTIONS_TURN_CUT_SERIOUS                         NUMBER(1)
 JUDGEMENT_OVER_SERIOUS                             NUMBER(1)
 JUDGEMENT_MEET_SERIOUS                             NUMBER(1)
 JUDGEMENT_CROSS_SERIOUS                            NUMBER(1)
 POSITIONING_NORMAL_SERIOUS                         NUMBER(1)
 POSITIONING_LANE_SERIOUS                           NUMBER(1)
 PEDESTRIAN_CROSSING_SERIOUS                        NUMBER(1)
 POSTITION_STOPS_SERIOUS                            NUMBER(1)
 AWARENESS_PLAN_SERIOUS                             NUMBER(1)
 ANCILLARY_CONTROLS_SERIOUS                         NUMBER(1)
 SPARE1_SERIOUS                                     NUMBER(1)
 SPARE2_SERIOUS                                     NUMBER(1)
 SPARE3_SERIOUS                                     NUMBER(1)
 SPARE4_SERIOUS                                     NUMBER(1)
 SPARE5_SERIOUS                                     NUMBER(1)
 H_CODE_SAFETY_DANGEROUS                            NUMBER(1)
 CONTROL_STOP_PROMPT_DANGEROUS                      NUMBER(1)
 CONTROL_STOP_CONTROL_DANGEROUS                     NUMBER(1)
 REV_LEFT_TRAIL_CONT_DANGEROUS                      NUMBER(1)
 REV_LEFT_TRAIL_OBSER_DANGEROUS                     NUMBER(1)
 REV_RIGHT_TRAIL_CONT_DANGER                        NUMBER(1)
 REV_RIGHT_TRAIL_OBSERV_DANGER                      NUMBER(1)
 REVERSE_PARK_CONTROL_DANGEROUS                     NUMBER(1)
 REVERSE_PARK_OBSERV_DANGEROUS                      NUMBER(1)
 TURN_IN_ROAD_CONT_DANGEROUS                        NUMBER(1)
 TURN_IN_ROAD_OBSERV_DANGEROUS                      NUMBER(1)
 VEHICLE_CHECKS_DANGEROUS                           NUMBER(1)
 TAXI_MAN_CONTROL_DANGEROUS                         NUMBER(1)
 TAXI_MAN_OBSERV_DANGEROUS                          NUMBER(1)
 TAXI_WHEELCHAIR_DANGEROUS                          NUMBER(1)
 UNCOUPLE_RECOUPLE_DANGEROUS                        NUMBER(1)
 PRECAUTIONS_DANGEROUS                              NUMBER(1)
 CONTROL_ACC_DANGEROUS                              NUMBER(1)
 CONTROL_CLUTCH_DANGEROUS                           NUMBER(1)
 CONTROL_GEARS_DANGEROUS                            NUMBER(1)
 CONTROL_FOOTBRAKE_DANGEROUS                        NUMBER(1)
 CONTROL_PARK_DANGEROUS                             NUMBER(1)
 CONTROL_STEERING_DANGEROUS                         NUMBER(1)
 CONTROL_BALANCE_DANGEROUS                          NUMBER(1)
 CONTROL_LGV_PCV_GEAR_DANGEROUS                     NUMBER(1)
 CONTROL_PCV_DOOR_DANGEROUS                         NUMBER(1)
 MOVE_OFF_SAFETY_DANGEROUS                          NUMBER(1)
 MOVE_OFF_CONTROL_DANGEROUS                         NUMBER(1)
 MIRRORS_MC_REAR_SIG_DANGEROUS                      NUMBER(1)
 MIRRORS_MC_REAR_DIR_DANGEROUS                      NUMBER(1)
 MIRRORS_MC_REAR_SPE_DANGEROUS                      NUMBER(1)
 SIGNALS_NECESSARY_DANGEROUS                        NUMBER(1)
 SIGNALS_CORRECTLY_DANGEROUS                        NUMBER(1)
 SIGNALS_TIMED_DANGEROUS                            NUMBER(1)
 CLEARANCE_OBSTRUCT_DANGEROUS                       NUMBER(1)
 RESPONSE_TRAF_SIGNS_DANGEROUS                      NUMBER(1)
 RESPONSE_ROAD_MARK_DANGEROUS                       NUMBER(1)
 RESPONSE_TRAF_LIGHT_DANGEROUS                      NUMBER(1)
 RESPONSE_TRAF_CONT_DANGEROUS                       NUMBER(1)
 RESPONSE_OTHER_DANGEROUS                           NUMBER(1)
 USE_OF_SPEED_DANGEROUS                             NUMBER(1)
 FOLLOWING_DISTANCE_DANGEROUS                       NUMBER(1)
 MAINTAIN_PROG_SPEED_DANGEROUS                      NUMBER(1)
 MAINTAIN_PROG_HES_DANGEROUS                        NUMBER(1)
 JUNCTIONS_SPEED_DANGEROUS                          NUMBER(1)
 JUNCTIONS_OBSERV_DANGEROUS                         NUMBER(1)
 JUNCTIONS_TURN_RIGHT_DANGEROUS                     NUMBER(1)
 JUNCTIONS_TURN_LEFT_DANGEROUS                      NUMBER(1)
 JUNCTIONS_TURN_CUT_DANGEROUS                       NUMBER(1)
 JUDGEMENT_OVER_DANGEROUS                           NUMBER(1)
 JUDGEMENT_MEET_DANGEROUS                           NUMBER(1)
 JUDGEMENT_CROSS_DANGEROUS                          NUMBER(1)
 POSITIONING_NORMAL_DANGEROUS                       NUMBER(1)
 POSITIONING_LANE_DANGEROUS                         NUMBER(1)
 PEDESTRIAN_CROSSING_DANGEROUS                      NUMBER(1)
 POSTITION_STOPS_DANGEROUS                          NUMBER(1)
 AWARENESS_PLAN_DANGEROUS                           NUMBER(1)
 ANCILLARY_CONTROLS_DANGEROUS                       NUMBER(1)
 SPARE1_DANGEROUS                                   NUMBER(1)
 SPARE2_DANGEROUS                                   NUMBER(1)
 SPARE3_DANGEROUS                                   NUMBER(1)
 SPARE4_DANGEROUS                                   NUMBER(1)
 SPARE5_DANGEROUS                                   NUMBER(1)
 CONTROL_STOP_COMPLETED                             NUMBER(1)
 REV_LEFT_TRAIL_COMPLETED                           NUMBER(1)
 REV_RIGHT_TRAIL_COMPLETED                          NUMBER(1)
 REVERSE_PARK_COMPLETED                             NUMBER(1)
 TURN_IN_ROAD_COMPLETED                             NUMBER(1)
 VEHICLE_CHECKS_COMPLETED                           NUMBER(1)
 TAXI_MANOEUVRE_COMPLETED                           NUMBER(1)
 TAXI_WHEELCHAIR_COMPLETED                          NUMBER(1)
 UNCOUPLE_RECOUPLE_COMPLETED                        NUMBER(1)
 CATEGORY_5_REVERSE_ROAD                            NUMBER(1)
 CATEGORY_5_REVERSE_CAR_PARK                        NUMBER(1)
 */
      `
      TEST_RESULT ,
      TOTAL_FAULTS,
      ROUTE_NUMBER,
      EXAMINER_ACTION_VERBAL,
      EXAMINER_ACTION_PHYSICAL,
      DUAL_CONTROL_IND,` +
 /*
 SURVEY_A_IND                                       VARCHAR2(1)
 SURVEY_B_IND                                       VARCHAR2(1)
 SURVEY_C_IND                                       VARCHAR2(1)
 SURVEY_D_IND                                       VARCHAR2(1)
 SURVEY_E_IND                                       VARCHAR2(1)
 SURVEY_F_IND                                       VARCHAR2(1)
 SURVEY_G_IND                                       VARCHAR2(1)
 SURVEY_H_IND                                       VARCHAR2(1)
 */
      `
      DEBRIEF_GIVEN,
      ACTIVITY_CODE,
      PASS_CERTIFICATE,
      LICENCE_RECEIVED,
      DOB,
      CANDIDATE_FORENAMES,
      GENDER,
      CANDIDATE_INDIVIDUAL_ID,
      CANDIDATE_POST_CODE,
      CANDIDATE_SURNAME,
      CANDIDATE_TITLE,
      DRIVER_NUMBER,` +
    // EXAMINER_FORENAMES
      `
      EXAMINER_PERSON_ID,` +
 /*
 EXAMINER_POST_CODE                                 VARCHAR2(8)
 EXAMINER_SURNAME                                   VARCHAR2(50)
 EXAMINER_TITLE                                     VARCHAR2(20)
 */
      `
      TEST_CATEGORY_REF,` +
 /*
 TEST_CENTRE_AREA_COST_CODE                         VARCHAR2(4)
 TEST_CENTRE_AREA_NAME                              VARCHAR2(50)
 TEST_CENTRE_COUNTRY_DESC                           VARCHAR2(20)
 TEST_CENTRE_COUNTRY_ID                             NUMBER(9)
 */
      `
      TEST_CENTRE_ID,` +
 /*
 TEST_CENTRE_LOCAL_AUTH_CODE                        VARCHAR2(6)
 TEST_CENTRE_LOCAL_AUTH_ID                          NUMBER(9)
 TEST_CENTRE_LOCAL_AUTH_NAME                        VARCHAR2(20)
 */
      `
      TEST_CENTRE_NAME,` +
 /*
 TEST_CENTRE_SECTOR_AREA_ID                         NUMBER(9)
 TEST_CENTRE_SECTOR_DESC                            VARCHAR2(50)
 TEST_CENTRE_SECTOR_ID                              NUMBER(9)
 TEST_CENTRE_MAIN_COST_CODE                         VARCHAR2(6)
 TEST_CENTRE_MAIN_LA_ID                             NUMBER(9)
 */
      `
      VEHICLE_SLOT_TYPE,
      WELSH_FORM_IND,` +
 /*
 IMAGE_REFERENCE                                    VARCHAR2(24)
 DATA_VALIDATION_FLAGS                              VARCHAR2(1500)
 AUDIT_DATA                                         CLOB
 TOTAL_DATA_KEYSTROKES                              NUMBER(6)
 TOTAL_FUNCTION_KEYSTROKES                          NUMBER(6)
 */
     `
      ETHNICITY,` +
 /*
 COA_LICENCE                                        NUMBER
 NO_LICENCE                                         NUMBER
 */
      `
      VEHICLE_REGISTRATION,
      ECO_SAFE_COMPLETED,
      ECO_SAFE_CONTROL,` +
// ?? ECO_SAFE_COVERED                                   NUMBER(1)
      `
      ECO_SAFE_PLANNING,` +
 /*
 INSTRUCTOR_CERT                                    NUMBER(7)
 MC_AVOIDANCE_DANGEROUS                             NUMBER(1)
 MC_AVOIDANCE_L                                     NUMBER(1)
 MC_AVOIDANCE_R                                     NUMBER(1)
 MC_AVOIDANCE_SERIOUS                               NUMBER(1)
 MC_AVOIDANCE_SPEED_FIRST                           NUMBER(2)
 MC_AVOIDANCE_SPEED_NOT_MET                         NUMBER(1)
 MC_AVOIDANCE_SPEED_SECOND                          NUMBER(2)
 MC_AVOIDANCE_TOTAL                                 NUMBER(2)
 MC_BENDS_DANGEROUS                                 NUMBER(1)
 MC_BENDS_SERIOUS                                   NUMBER(1)
 MC_BENDS_TOTAL                                     NUMBER(2)
 MC_DL196_CBT_CERT_NO                               NUMBER(8)
 MC_EMERGENCY_STOP_SPEED_FIRST                      NUMBER(2)
 MC_EMERGENCY_STOP_SPEED_SECOND                     NUMBER(2)
 MC_EMER_STOP_SPEED_NOT_MET                         NUMBER(1)
 MC_MANUAL_HANDLING_DANGEROUS                       NUMBER(1)
 MC_MANUAL_HANDLING_SERIOUS                         NUMBER(1)
 MC_MANUAL_HANDLING_TOTAL                           NUMBER(2)
 MC_SLALOM_DANGEROUS                                NUMBER(1)
 MC_SLALOM_SERIOUS                                  NUMBER(1)
 MC_SLALOM_TOTAL                                    NUMBER(2)
 MC_SLOW_CONTROL_DANGEROUS                          NUMBER(1)
 MC_SLOW_CONTROL_SERIOUS                            NUMBER(1)
 MC_SLOW_CONTROL_TOTAL                              NUMBER(2)
 MC_USE_OF_STAND_DANGEROUS                          NUMBER(1)
 MC_USE_OF_STAND_SERIOUS                            NUMBER(1)
 MC_USE_OF_STAND_TOTAL                              NUMBER(2)
 MC_UTURN_DANGEROUS                                 NUMBER(1)
 MC_UTURN_SERIOUS                                   NUMBER(1)
 MC_UTURN_TOTAL                                     NUMBER(2)
 SPARE6_DANGEROUS                                   NUMBER(1)
 SPARE6_SERIOUS                                     NUMBER(1)
 SPARE6_TOTAL                                       NUMBER(2)
 */
      `
   ) values (` +
      // TODO: insert right number of ? here...
      `
   )`;

  // SQL statement values
  // TODO: check the enum values get mapped properly, if not convert to union literals
  const values = [
    // TODO: testResult.channelIndicator => add channel indicator
//  REC_TYPE                                           NUMBER(1)
//  REC_NO                                             NUMBER(6)
//  FORM_TYPE                                          NUMBER(1)
    testResult.drivingSchoolCar, // DRIVING_SCHOOL_CANDIDATE  NUMBER(1)
    testResult.d255, // SPECIAL_NEEDS  NUMBER(1)
    testResult.applicationReference, // APP_REF_NO  NUMBER(12)
// DRIVER_NO_DOB                                      NUMBER(6)
    testResult.testDate, // format date into => DATE_OF_TEST  VARCHAR2(6)
    testResult.testTime, // format time into => TIME  VARCHAR2(4)
    testResult.testCentreCostCode, // DTC_AUTHORITY_CODE  VARCHAR2(6)
    testResult.staffNumber, // STAFF_NO  VARCHAR2(10)
    testResult.testCategory, // TEST_CATEGORY_TYPE  VARCHAR2(4)
    testResult.automatic, // AUTOMATIC_TEST  VARCHAR2(1)
    testResult.extended, // EXTENDED_TEST  VARCHAR2(1)
    testResult.testType,  // TEST_TYPE  NUMBER
    testResult.instructorPRN, // ADI_NUMBER  VARCHAR2(7)
// ADI_REF_CODE                                       VARCHAR2(3)
    testResult.supervisorAccompanied, // ACCOMPANIED_BY_DSA  NUMBER(1)
    testResult.instructorAccompanied, // ACCOMPANIED_BY_ADI  NUMBER(1)
    testResult.interpreterAccompanied, // ACCOMPANIED_BY_INTERPRETER  NUMBER(1)
    testResult.otherAccompanied, // ACCOMPANIED_BY_OTHER  NUMBER(1)
    testResult.visitingExaminer, // VISITING_EXAMINER  NUMBER(1)
    testResult.change, // SHORT_NOTICE_EXAMINER  NUMBER(1)
//  EYESIGHT_SERIOUS                                   NUMBER(1)
//  H_CODE_SAFETY_TOTAL                                NUMBER(2)
//  CONTROL_STOP_PROMPT_TOTAL                          NUMBER(2)
//  CONTROL_STOP_CONTROL_TOTAL                         NUMBER(2)
//  REV_LEFT_TRAIL_CONT_TOTAL                          NUMBER(2)
//  REV_LEFT_TRAIL_OBSERV_TOTAL                        NUMBER(2)
//  REV_RIGHT_TRAIL_CONT_TOTAL                         NUMBER(2)
//  REV_RIGHT_TRAIL_OBSERV_TOTAL                       NUMBER(2)
//  REVERSE_PARK_CONT_TOTAL                            NUMBER(2)
//  REVERSE_PARK_OBSERV_TOTAL                          NUMBER(2)
//  TURN_IN_ROAD_CONT_TOTAL                            NUMBER(2)
//  TURN_IN_ROAD_OBSERV_TOTAL                          NUMBER(2)
//  VEHICLE_CHECKS_TOTAL                               NUMBER(2)
//  TAXI_MAN_CONTROL_TOTAL                             NUMBER(2)
//  TAXI_MAN_OBSERV_TOTAL                              NUMBER(2)
//  TAXI_WHEELCHAIR_TOTAL                              NUMBER(2)
//  UNCOUPLE_RECOUPLE_TOTAL                            NUMBER(2)
//  PRECAUTIONS_TOTAL                                  NUMBER(2)
//  CONTROL_ACC_TOTAL                                  NUMBER(2)
//  CONTROL_CLUTCH_TOTAL                               NUMBER(2)
//  CONTROL_GEARS_TOTAL                                NUMBER(2)
//  CONTROL_FOOTBRAKE_TOTAL                            NUMBER(2)
//  CONTROL_PARK_TOTAL                                 NUMBER(2)
//  CONTROL_STEERING_TOTAL                             NUMBER(2)
//  CONTROL_BALANCE_TOTAL                              NUMBER(2)
//  CONTROL_LGV_PCV_GEAR_TOTAL                         NUMBER(2)
//  CONTROL_PCV_DOOR_TOTAL                             NUMBER(2)
//  MOVE_OFF_SAFETY_TOTAL                              NUMBER(2)
//  MOVE_OFF_CONTROL_TOTAL                             NUMBER(2)
//  MIRRORS_MC_REAR_SIG_TOTAL                          NUMBER(2)
//  MIRRORS_MC_REAR_DIR_TOTAL                          NUMBER(2)
//  MIRRORS_MC_REAR_SPE_TOTAL                          NUMBER(2)
//  SIGNALS_NECESSARY_TOTAL                            NUMBER(2)
//  SIGNALS_CORRECTLY_TOTAL                            NUMBER(2)
//  SIGNALS_TIMED_TOTAL                                NUMBER(2)
//  CLEARANCE_OBSTRUCT_TOTAL                           NUMBER(2)
//  RESPONSE_TRAF_SIGNS_TOTAL                          NUMBER(2)
//  RESPONSE_ROAD_MARK_TOTAL                           NUMBER(2)
//  RESPONSE_TRAF_LIGHT_TOTAL                          NUMBER(2)
//  RESPONSE_TRAF_CONT_TOTAL                           NUMBER(2)
//  RESPONSE_OTHER_TOTAL                               NUMBER(2)
//  USE_OF_SPEED_TOTAL                                 NUMBER(2)
//  FOLLOWING_DISTANCE_TOTAL                           NUMBER(2)
//  MAINTAIN_PROG_SPEED_TOTAL                          NUMBER(2)
//  MAINTAIN_PROG_HES_TOTAL                            NUMBER(2)
//  JUNCTIONS_SPEED_TOTAL                              NUMBER(2)
//  JUNCTIONS_OBSERV_TOTAL                             NUMBER(2)
//  JUNCTIONS_TURN_RIGHT_TOTAL                         NUMBER(2)
//  JUNCTIONS_TURN_LEFT_TOTAL                          NUMBER(2)
//  JUNCTIONS_TURN_CUT_TOTAL                           NUMBER(2)
//  JUDGEMENT_OVER_TOTAL                               NUMBER(2)
//  JUDGEMENT_MEET_TOTAL                               NUMBER(2)
//  JUDGEMENT_CROSS_TOTAL                              NUMBER(2)
//  POSITIONING_NORMAL_TOTAL                           NUMBER(2)
//  POSITIONING_LANE_TOTAL                             NUMBER(2)
//  PEDESTRIAN_CROSSING_TOTAL                          NUMBER(2)
//  POSTITION_STOPS_TOTAL                              NUMBER(2)
//  AWARENESS_PLAN_TOTAL                               NUMBER(2)
//  ANCILLARY_CONTROLS_TOTAL                           NUMBER(2)
//  SPARE1_TOTAL                                       NUMBER(2)
//  SPARE2_TOTAL                                       NUMBER(2)
//  SPARE3_TOTAL                                       NUMBER(2)
//  SPARE4_TOTAL                                       NUMBER(2)
//  SPARE5_TOTAL                                       NUMBER(2)
//  H_CODE_SAFETY_SERIOUS                              NUMBER(1)
//  CONTROL_STOP_PROMPT_SERIOUS                        NUMBER(1)
//  CONTROL_STOP_CONTROL_SERIOUS                       NUMBER(1)
//  REV_LEFT_TRAIL_CONT_SERIOUS                        NUMBER(1)
//  REV_LEFT_TRAIL_OBSERV_SERIOUS                      NUMBER(1)
//  REV_RIGHT_TRAIL_CONT_SERIOUS                       NUMBER(1)
//  REV_RIGHT_TRAIL_OBSERV_SERIOUS                     NUMBER(1)
//  REVERSE_PARK_CONT_SERIOUS                          NUMBER(1)
//  REVERSE_PARK_OBSERV_SERIOUS                        NUMBER(1)
//  TURN_IN_ROAD_CONT_SERIOUS                          NUMBER(1)
//  TURN_IN_ROAD_OBSERV_SERIOUS                        NUMBER(1)
//  VEHICLE_CHECKS_SERIOUS                             NUMBER(1)
//  TAXI_MAN_CONTROL_SERIOUS                           NUMBER(1)
//  TAXI_MAN_OBSERV_SERIOUS                            NUMBER(1)
//  TAXI_WHEELCHAIR_SERIOUS                            NUMBER(1)
//  UNCOUPLE_RECOUPLE_SERIOUS                          NUMBER(1)
//  PRECAUTIONS_SERIOUS                                NUMBER(1)
//  CONTROL_ACC_SERIOUS                                NUMBER(1)
//  CONTROL_CLUTCH_SERIOUS                             NUMBER(1)
//  CONTROL_GEARS_SERIOUS                              NUMBER(1)
//  CONTROL_FOOTBRAKE_SERIOUS                          NUMBER(1)
//  CONTROL_PARK_SERIOUS                               NUMBER(1)
//  CONTROL_STEERING_SERIOUS                           NUMBER(1)
//  CONTROL_BALANCE_SERIOUS                            NUMBER(1)
//  CONTROL_LGV_PCV_GEAR_SERIOUS                       NUMBER(1)
//  CONTROL_PCV_DOOR_SERIOUS                           NUMBER(1)
//  MOVE_OFF_SAFETY_SERIOUS                            NUMBER(1)
//  MOVE_OFF_CONTROL_SERIOUS                           NUMBER(1)
//  MIRRORS_MC_REAR_SIG_SERIOUS                        NUMBER(1)
//  MIRRORS_MC_REAR_DIR_SERIOUS                        NUMBER(1)
//  MIRRORS_MC_REAR_SPE_SERIOUS                        NUMBER(1)
//  SIGNALS_NECESSARY_SERIOUS                          NUMBER(1)
//  SIGNALS_CORRECTLY_SERIOUS                          NUMBER(1)
//  SIGNALS_TIMED_SERIOUS                              NUMBER(1)
//  CLEARANCE_OBSTRUCT_SERIOUS                         NUMBER(1)
//  RESPONSE_TRAF_SIGNS_SERIOUS                        NUMBER(1)
//  RESPONSE_ROAD_MARK_SERIOUS                         NUMBER(1)
//  RESPONSE_TRAF_LIGHT_SERIOUS                        NUMBER(1)
//  RESPONSE_TRAF_CONT_SERIOUS                         NUMBER(1)
//  RESPONSE_OTHER_SERIOUS                             NUMBER(1)
//  USE_OF_SPEED_SERIOUS                               NUMBER(1)
//  FOLLOWING_DISTANCE_SERIOUS                         NUMBER(1)
//  MAINTAIN_PROG_SPEED_SERIOUS                        NUMBER(1)
//  MAINTAIN_PROG_HES_SERIOUS                          NUMBER(1)
//  JUNCTIONS_SPEED_SERIOUS                            NUMBER(1)
//  JUNCTIONS_OBSERV_SERIOUS                           NUMBER(1)
//  JUNCTIONS_TURN_RIGHT_SERIOUS                       NUMBER(1)
//  JUNCTIONS_TURN_LEFT_SERIOUS                        NUMBER(1)
//  JUNCTIONS_TURN_CUT_SERIOUS                         NUMBER(1)
//  JUDGEMENT_OVER_SERIOUS                             NUMBER(1)
//  JUDGEMENT_MEET_SERIOUS                             NUMBER(1)
//  JUDGEMENT_CROSS_SERIOUS                            NUMBER(1)
//  POSITIONING_NORMAL_SERIOUS                         NUMBER(1)
//  POSITIONING_LANE_SERIOUS                           NUMBER(1)
//  PEDESTRIAN_CROSSING_SERIOUS                        NUMBER(1)
//  POSTITION_STOPS_SERIOUS                            NUMBER(1)
//  AWARENESS_PLAN_SERIOUS                             NUMBER(1)
//  ANCILLARY_CONTROLS_SERIOUS                         NUMBER(1)
//  SPARE1_SERIOUS                                     NUMBER(1)
//  SPARE2_SERIOUS                                     NUMBER(1)
//  SPARE3_SERIOUS                                     NUMBER(1)
//  SPARE4_SERIOUS                                     NUMBER(1)
//  SPARE5_SERIOUS                                     NUMBER(1)
//  H_CODE_SAFETY_DANGEROUS                            NUMBER(1)
//  CONTROL_STOP_PROMPT_DANGEROUS                      NUMBER(1)
//  CONTROL_STOP_CONTROL_DANGEROUS                     NUMBER(1)
//  REV_LEFT_TRAIL_CONT_DANGEROUS                      NUMBER(1)
//  REV_LEFT_TRAIL_OBSER_DANGEROUS                     NUMBER(1)
//  REV_RIGHT_TRAIL_CONT_DANGER                        NUMBER(1)
//  REV_RIGHT_TRAIL_OBSERV_DANGER                      NUMBER(1)
//  REVERSE_PARK_CONTROL_DANGEROUS                     NUMBER(1)
//  REVERSE_PARK_OBSERV_DANGEROUS                      NUMBER(1)
//  TURN_IN_ROAD_CONT_DANGEROUS                        NUMBER(1)
//  TURN_IN_ROAD_OBSERV_DANGEROUS                      NUMBER(1)
//  VEHICLE_CHECKS_DANGEROUS                           NUMBER(1)
//  TAXI_MAN_CONTROL_DANGEROUS                         NUMBER(1)
//  TAXI_MAN_OBSERV_DANGEROUS                          NUMBER(1)
//  TAXI_WHEELCHAIR_DANGEROUS                          NUMBER(1)
//  UNCOUPLE_RECOUPLE_DANGEROUS                        NUMBER(1)
//  PRECAUTIONS_DANGEROUS                              NUMBER(1)
//  CONTROL_ACC_DANGEROUS                              NUMBER(1)
//  CONTROL_CLUTCH_DANGEROUS                           NUMBER(1)
//  CONTROL_GEARS_DANGEROUS                            NUMBER(1)
//  CONTROL_FOOTBRAKE_DANGEROUS                        NUMBER(1)
//  CONTROL_PARK_DANGEROUS                             NUMBER(1)
//  CONTROL_STEERING_DANGEROUS                         NUMBER(1)
//  CONTROL_BALANCE_DANGEROUS                          NUMBER(1)
//  CONTROL_LGV_PCV_GEAR_DANGEROUS                     NUMBER(1)
//  CONTROL_PCV_DOOR_DANGEROUS                         NUMBER(1)
//  MOVE_OFF_SAFETY_DANGEROUS                          NUMBER(1)
//  MOVE_OFF_CONTROL_DANGEROUS                         NUMBER(1)
//  MIRRORS_MC_REAR_SIG_DANGEROUS                      NUMBER(1)
//  MIRRORS_MC_REAR_DIR_DANGEROUS                      NUMBER(1)
//  MIRRORS_MC_REAR_SPE_DANGEROUS                      NUMBER(1)
//  SIGNALS_NECESSARY_DANGEROUS                        NUMBER(1)
//  SIGNALS_CORRECTLY_DANGEROUS                        NUMBER(1)
//  SIGNALS_TIMED_DANGEROUS                            NUMBER(1)
//  CLEARANCE_OBSTRUCT_DANGEROUS                       NUMBER(1)
//  RESPONSE_TRAF_SIGNS_DANGEROUS                      NUMBER(1)
//  RESPONSE_ROAD_MARK_DANGEROUS                       NUMBER(1)
//  RESPONSE_TRAF_LIGHT_DANGEROUS                      NUMBER(1)
//  RESPONSE_TRAF_CONT_DANGEROUS                       NUMBER(1)
//  RESPONSE_OTHER_DANGEROUS                           NUMBER(1)
//  USE_OF_SPEED_DANGEROUS                             NUMBER(1)
//  FOLLOWING_DISTANCE_DANGEROUS                       NUMBER(1)
//  MAINTAIN_PROG_SPEED_DANGEROUS                      NUMBER(1)
//  MAINTAIN_PROG_HES_DANGEROUS                        NUMBER(1)
//  JUNCTIONS_SPEED_DANGEROUS                          NUMBER(1)
//  JUNCTIONS_OBSERV_DANGEROUS                         NUMBER(1)
//  JUNCTIONS_TURN_RIGHT_DANGEROUS                     NUMBER(1)
//  JUNCTIONS_TURN_LEFT_DANGEROUS                      NUMBER(1)
//  JUNCTIONS_TURN_CUT_DANGEROUS                       NUMBER(1)
//  JUDGEMENT_OVER_DANGEROUS                           NUMBER(1)
//  JUDGEMENT_MEET_DANGEROUS                           NUMBER(1)
//  JUDGEMENT_CROSS_DANGEROUS                          NUMBER(1)
//  POSITIONING_NORMAL_DANGEROUS                       NUMBER(1)
//  POSITIONING_LANE_DANGEROUS                         NUMBER(1)
//  PEDESTRIAN_CROSSING_DANGEROUS                      NUMBER(1)
//  POSTITION_STOPS_DANGEROUS                          NUMBER(1)
//  AWARENESS_PLAN_DANGEROUS                           NUMBER(1)
//  ANCILLARY_CONTROLS_DANGEROUS                       NUMBER(1)
//  SPARE1_DANGEROUS                                   NUMBER(1)
//  SPARE2_DANGEROUS                                   NUMBER(1)
//  SPARE3_DANGEROUS                                   NUMBER(1)
//  SPARE4_DANGEROUS                                   NUMBER(1)
//  SPARE5_DANGEROUS                                   NUMBER(1)
//  CONTROL_STOP_COMPLETED                             NUMBER(1)
//  REV_LEFT_TRAIL_COMPLETED                           NUMBER(1)
//  REV_RIGHT_TRAIL_COMPLETED                          NUMBER(1)
//  REVERSE_PARK_COMPLETED                             NUMBER(1)
//  TURN_IN_ROAD_COMPLETED                             NUMBER(1)
//  VEHICLE_CHECKS_COMPLETED                           NUMBER(1)
//  TAXI_MANOEUVRE_COMPLETED                           NUMBER(1)
//  TAXI_WHEELCHAIR_COMPLETED                          NUMBER(1)
//  UNCOUPLE_RECOUPLE_COMPLETED                        NUMBER(1)
//  CATEGORY_5_REVERSE_ROAD                            NUMBER(1)
//  CATEGORY_5_REVERSE_CAR_PARK                        NUMBER(1)
    testResult.result, // TEST_RESULT  VARCHAR2(1)
    testResult.totalFaults, // TOTAL_FAULTS  NUMBER(2)
    testResult.route, // ROUTE_NUMBER  NUMBER(2)
    testResult.etaVerbal, // EXAMINER_ACTION_VERBAL  NUMBER(1)
    testResult.etaPhysical, // EXAMINER_ACTION_PHYSICAL  NUMBER(1)
    testResult.dualControls, // DUAL_CONTROL_IND  NUMBER(1)
//  SURVEY_A_IND                                       VARCHAR2(1)
//  SURVEY_B_IND                                       VARCHAR2(1)
//  SURVEY_C_IND                                       VARCHAR2(1)
//  SURVEY_D_IND                                       VARCHAR2(1)
//  SURVEY_E_IND                                       VARCHAR2(1)
//  SURVEY_F_IND                                       VARCHAR2(1)
//  SURVEY_G_IND                                       VARCHAR2(1)
//  SURVEY_H_IND                                       VARCHAR2(1)
    testResult.debriefGiven, // DEBRIEF_GIVEN  NUMBER(1)
    testResult.activityCode, // ACTIVITY_CODE  NUMBER(3)
    testResult.passCertificateNumber, // PASS_CERTIFICATE  VARCHAR2(8)
    testResult.licenseReceived, // LICENCE_RECEIVED  NUMBER(1)
    testResult.candidateDOB, // DOB  DATE
    testResult.candidateForenames, // CANDIDATE_FORENAMES  VARCHAR2(50)
    testResult.candidateGender, // GENDER  VARCHAR2(1)
    testResult.candidateIndividualId, // CANDIDATE_INDIVIDUAL_ID  NUMBER(9)
    testResult.candidatePostCode, // CANDIDATE_POST_CODE  VARCHAR2(8)
    testResult.candidateSurname, // CANDIDATE_SURNAME  VARCHAR2(50)
    testResult.candidateTitle, // CANDIDATE_TITLE  VARCHAR2(20)
    testResult.driverNumber, // DRIVER_NUMBER  VARCHAR2(20)
// EXAMINER_FORENAMES                                 VARCHAR2(50)
    testResult.examinerIndividualId, // EXAMINER_PERSON_ID  NUMBER(9)
//  EXAMINER_POST_CODE                                 VARCHAR2(8)
//  EXAMINER_SURNAME                                   VARCHAR2(50)
//  EXAMINER_TITLE                                     VARCHAR2(20)
    testResult.bookedTestCategory, // TEST_CATEGORY_REF  VARCHAR2(10)
//  TEST_CENTRE_AREA_COST_CODE                         VARCHAR2(4)
//  TEST_CENTRE_AREA_NAME                              VARCHAR2(50)
//  TEST_CENTRE_COUNTRY_DESC                           VARCHAR2(20)
//  TEST_CENTRE_COUNTRY_ID                             NUMBER(9)
    testResult.testCentreId, // TEST_CENTRE_ID  NUMBER(9)
//  TEST_CENTRE_LOCAL_AUTH_CODE                        VARCHAR2(6)
//  TEST_CENTRE_LOCAL_AUTH_ID                          NUMBER(9)
//  TEST_CENTRE_LOCAL_AUTH_NAME                        VARCHAR2(20)
    testResult.testCentreName, // TEST_CENTRE_NAME  VARCHAR2(50)
//  TEST_CENTRE_SECTOR_AREA_ID                         NUMBER(9)
//  TEST_CENTRE_SECTOR_DESC                            VARCHAR2(50)
//  TEST_CENTRE_SECTOR_ID                              NUMBER(9)
//  TEST_CENTRE_MAIN_COST_CODE                         VARCHAR2(6)
//  TEST_CENTRE_MAIN_LA_ID                             NUMBER(9)
    testResult.vehicleSlotType, // VEHICLE_SLOT_TYPE  VARCHAR2(2)
    testResult.language, // WELSH_FORM_IND  VARCHAR2(1)
//  IMAGE_REFERENCE                                    VARCHAR2(24)
//  DATA_VALIDATION_FLAGS                              VARCHAR2(1500)
//  AUDIT_DATA                                         CLOB
//  TOTAL_DATA_KEYSTROKES                              NUMBER(6)
//  TOTAL_FUNCTION_KEYSTROKES                          NUMBER(6)
    testResult.ethnicityCode, // ETHNICITY  VARCHAR2(1)
//  COA_LICENCE                                        NUMBER
//  NO_LICENCE                                         NUMBER
    testResult.vehicleRegistration, // VEHICLE_REGISTRATION  VARCHAR2(7)
    testResult.ecoAssessed, // ??? ECO_SAFE_COMPLETED  NUMBER(1)
    testResult.ecoControl, // ECO_SAFE_CONTROL  NUMBER(1)
// ??? ECO_SAFE_COVERED                                   NUMBER(1)
    testResult.ecoPlanning, // ECO_SAFE_PLANNING  NUMBER(1)
//  INSTRUCTOR_CERT                                    NUMBER(7)
//  MC_AVOIDANCE_DANGEROUS                             NUMBER(1)
//  MC_AVOIDANCE_L                                     NUMBER(1)
//  MC_AVOIDANCE_R                                     NUMBER(1)
//  MC_AVOIDANCE_SERIOUS                               NUMBER(1)
//  MC_AVOIDANCE_SPEED_FIRST                           NUMBER(2)
//  MC_AVOIDANCE_SPEED_NOT_MET                         NUMBER(1)
//  MC_AVOIDANCE_SPEED_SECOND                          NUMBER(2)
//  MC_AVOIDANCE_TOTAL                                 NUMBER(2)
//  MC_BENDS_DANGEROUS                                 NUMBER(1)
//  MC_BENDS_SERIOUS                                   NUMBER(1)
//  MC_BENDS_TOTAL                                     NUMBER(2)
//  MC_DL196_CBT_CERT_NO                               NUMBER(8)
//  MC_EMERGENCY_STOP_SPEED_FIRST                      NUMBER(2)
//  MC_EMERGENCY_STOP_SPEED_SECOND                     NUMBER(2)
//  MC_EMER_STOP_SPEED_NOT_MET                         NUMBER(1)
//  MC_MANUAL_HANDLING_DANGEROUS                       NUMBER(1)
//  MC_MANUAL_HANDLING_SERIOUS                         NUMBER(1)
//  MC_MANUAL_HANDLING_TOTAL                           NUMBER(2)
//  MC_SLALOM_DANGEROUS                                NUMBER(1)
//  MC_SLALOM_SERIOUS                                  NUMBER(1)
//  MC_SLALOM_TOTAL                                    NUMBER(2)
//  MC_SLOW_CONTROL_DANGEROUS                          NUMBER(1)
//  MC_SLOW_CONTROL_SERIOUS                            NUMBER(1)
//  MC_SLOW_CONTROL_TOTAL                              NUMBER(2)
//  MC_USE_OF_STAND_DANGEROUS                          NUMBER(1)
//  MC_USE_OF_STAND_SERIOUS                            NUMBER(1)
//  MC_USE_OF_STAND_TOTAL                              NUMBER(2)
//  MC_UTURN_DANGEROUS                                 NUMBER(1)
//  MC_UTURN_SERIOUS                                   NUMBER(1)
//  MC_UTURN_TOTAL                                     NUMBER(2)
//  SPARE6_DANGEROUS                                   NUMBER(1)
//  SPARE6_SERIOUS                                     NUMBER(1)
//  SPARE6_TOTAL                                       NUMBER(2)
  ];
};
