import { DataField } from '../../../../../../domain/mi-export-data';

export function getCatAMod1FullyPopulatedDangerousFaultDataFields(): DataField[] {
  return [
    { col: 'MC_USE_OF_STAND_DANGEROUS', val: 0 },
    { col: 'MC_USE_OF_STAND_SERIOUS', val: 0 },
    { col: 'MC_USE_OF_STAND_TOTAL', val: 0 },
    { col: 'MC_MANUAL_HANDLING_DANGEROUS', val: 0 },
    { col: 'MC_MANUAL_HANDLING_SERIOUS', val: 0 },
    { col: 'MC_MANUAL_HANDLING_TOTAL', val: 0 },
    { col: 'MC_SLALOM_DANGEROUS', val: 0 },
    { col: 'MC_SLALOM_SERIOUS', val: 0 },
    { col: 'MC_SLALOM_TOTAL', val: 0 },
    { col: 'MC_SLOW_CONTROL_DANGEROUS', val: 0 },
    { col: 'MC_SLOW_CONTROL_SERIOUS', val: 0 },
    { col: 'MC_SLOW_CONTROL_TOTAL', val: 0 },
    { col: 'MC_UTURN_DANGEROUS', val: 0 },
    { col: 'MC_UTURN_SERIOUS', val: 0 },
    { col: 'MC_UTURN_TOTAL', val: 0 },
    { col: 'SPARE1_DANGEROUS', val: 0 },
    { col: 'SPARE1_SERIOUS', val: 0 },
    { col: 'SPARE1_TOTAL', val: 0 },
    { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
    { col: 'CONTROL_STOP_PROMPT_SERIOUS', val: 0 },
    { col: 'CONTROL_STOP_PROMPT_TOTAL', val: 0 },
    { col: 'MC_AVOIDANCE_DANGEROUS', val: 0 },
    { col: 'MC_AVOIDANCE_SERIOUS', val: 0 },
    { col: 'MC_AVOIDANCE_TOTAL', val: 0 },
    { col: 'PRECAUTIONS_DANGEROUS', val: 1 },
    { col: 'PRECAUTIONS_SERIOUS', val: 0 },
    { col: 'PRECAUTIONS_TOTAL', val: 0 },
    { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 1 },
    { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
    { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 1 },
    { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
    { col: 'MC_AVOIDANCE_SPEED_NOT_MET', val: 0 },
    { col: 'MC_EMER_STOP_SPEED_NOT_MET', val: 0 },
    { col: 'MC_DL196_CBT_CERT_NO', val: '123456' },
    { col: 'MC_AVOIDANCE_L', val: 0 },
    { col: 'MC_AVOIDANCE_R', val: 0 },
    { col: 'MC_AVOIDANCE_SPEED_FIRST', val: 50 },
    { col: 'MC_EMERGENCY_STOP_SPEED_FIRST', val: 50 },

  ];
}
