import { DataField } from '../../../../../../domain/mi-export-data';

export function getFullyPopulatedFaultDataFields(): DataField[] {
  return [
    { col: 'CONTROL_ACC_TOTAL', val: 1 },
    { col: 'CONTROL_CLUTCH_TOTAL', val: 2 },
    { col: 'CONTROL_GEARS_TOTAL', val: 3 },
    { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
    { col: 'CONTROL_PARK_TOTAL', val: 0 },
    { col: 'CONTROL_STEERING_TOTAL', val: 6 },
    { col: 'CONTROL_BALANCE_TOTAL', val: 7 },
    { col: 'MOVE_OFF_SAFETY_TOTAL', val: 10 },
    { col: 'MOVE_OFF_CONTROL_TOTAL', val: 11 },
    { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 12 },
    { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 13 },
    { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 14 },
    { col: 'SIGNALS_NECESSARY_TOTAL', val: 15 },
    { col: 'SIGNALS_CORRECTLY_TOTAL', val: 16 },
    { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 28 },
    { col: 'SIGNALS_TIMED_TOTAL', val: 1 },
    { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 1 },
    { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 1 },
    { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 1 },
    { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 1 },
    { col: 'RESPONSE_OTHER_TOTAL', val: 1 },
    { col: 'USE_OF_SPEED_TOTAL', val: 30 },
    { col: 'FOLLOWING_DISTANCE_TOTAL', val: 29 },
    { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 31 },
    { col: 'MAINTAIN_PROG_HES_TOTAL', val: 32 },
    { col: 'JUNCTIONS_SPEED_TOTAL', val: 18 },
    { col: 'JUNCTIONS_OBSERV_TOTAL', val: 19 },
    { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 20 },
    { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 21 },
    { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 22 },
    { col: 'JUDGEMENT_OVER_TOTAL', val: 23 },
    { col: 'JUDGEMENT_MEET_TOTAL', val: 24 },
    { col: 'JUDGEMENT_CROSS_TOTAL', val: 25 },
    { col: 'POSITIONING_NORMAL_TOTAL', val: 26 },
    { col: 'POSITIONING_LANE_TOTAL', val: 27 },
    { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 38 },
    { col: 'POSTITION_STOPS_TOTAL', val: 39 },
    { col: 'AWARENESS_PLAN_TOTAL', val: 40 },
    { col: 'ANCILLARY_CONTROLS_TOTAL', val: 8 },
    { col: 'CONTROL_ACC_SERIOUS', val: 0 },
    { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
    { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
    { col: 'CONTROL_PARK_SERIOUS', val: 0 },
    { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
    { col: 'CONTROL_BALANCE_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
    { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
    { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
    { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
    { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
    { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
    { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
    { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
    { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
    { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
    { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
    { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
    { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
    { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
    { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
    { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
    { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
    { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
    { col: 'CONTROL_BALANCE_DANGEROUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
    { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
    { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
    { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
    { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
    { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
    { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
    { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
    { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
    { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
    { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
    { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
    { col: 'EYESIGHT_SERIOUS', val: 0 },
    { col: 'EYESIGHT_COMPLETED', val: 1 },
    { col: 'VEHICLE_CHECKS_TOTAL', val: 2 },
    { col: 'VEHICLE_CHECKS_COMMENT', val: 'candidate fell off the bike' },
    { col: 'PRECAUTIONS_COMMENT', val: 'precautionsComments' },
    { col: 'CONTROL_ACC_COMMENT', val: 'controlsThrottleComments' },
    { col: 'CONTROL_CLUTCH_COMMENT', val: 'controlsClutchComments' },
    { col: 'CONTROL_GEARS_COMMENT', val: 'controlsGearsComments' },
    { col: 'CONTROL_STEERING_COMMENT', val: 'controlsSteeringComments' },
    { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'moveOffSafetyComments' },
    { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'moveOffControlComments' },
    { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'useOfMirrorsSignallingComments' },
    { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'useOfMirrorsChangeDirectionComments' },
    { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'useOfMirrorsChangeSpeedComments' },
    { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signalsNecessaryComments' },
    { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signalsCorrectlyComments' },
    { col: 'SIGNALS_TIMED_COMMENT', val: 'signalsTimedComments' },
    { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearanceOrObstructionsComments' },
    { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'responseToSignsTrafficSignsComments' },
    { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'responseToSignsRoadMarkingsComments' },
    { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'responseToSignsTrafficLightsComments' },
    { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'responseToSignsTrafficControllersComments' },
    { col: 'RESPONSE_OTHER_COMMENT', val: 'responseToSignsOtherRoadUsersComments' },
    { col: 'USE_OF_SPEED_COMMENT', val: 'useOfSpeedComments' },
    { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'followingDistanceComments' },
    { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progressAppropriateSpeedComments' },
    { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progressUndueHesitationComments' },
    { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctionsApproachSpeedComments' },
    { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctionsObservationComments' },
    { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctionsTurningRightComments' },
    { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctionsTurningLeftComments' },
    { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctionsCuttingCornersComments' },
    { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgementOvertakingComments' },
    { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgementMeetingComments' },
    { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgementCrossingComments' },
    { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioningNormalDrivingComments' },
    { col: 'POSITIONING_LANE_COMMENT', val: 'positioningLaneDisciplineComments' },
    { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrianCrossingsComments' },
    { col: 'POSITION_STOPS_COMMENT', val: 'positionNormalStopsComments' },
    { col: 'AWARENESS_PLAN_COMMENT', val: 'awarenessPlanningComments' },
    { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillaryControlsComments' },
    { col: 'INDEPENDENT_DRIVING', val: 'Sat nav' },
    { col: 'SAFETY_1_CODE', val: 'SQ4' },
    { col: 'SAFETY_1_DESCRIPTION', val: 'Lights' },
    { col: 'SAFETY_2_CODE', val: 'SQ10' },
    { col: 'SAFETY_2_DESCRIPTION', val: 'Brakes' },
    { col: 'BALANCE_1_CODE', val: 'BQ3' },
    { col: 'BALANCE_1_DESCRIPTION', val: 'Balance with passenger' },
  ];
}

export function getFullyPopulatedSeriousDataFields(): DataField[] {
  return [
    { col: 'CONTROL_ACC_TOTAL', val: 0 },
    { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
    { col: 'CONTROL_GEARS_TOTAL', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
    { col: 'CONTROL_PARK_TOTAL', val: 0 },
    { col: 'CONTROL_STEERING_TOTAL', val: 0 },
    { col: 'CONTROL_BALANCE_TOTAL', val: 0 },
    { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
    { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
    { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
    { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
    { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
    { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
    { col: 'USE_OF_SPEED_TOTAL', val: 0 },
    { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
    { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
    { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
    { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
    { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
    { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
    { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
    { col: 'POSITIONING_LANE_TOTAL', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
    { col: 'POSTITION_STOPS_TOTAL', val: 0 },
    { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
    { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
    { col: 'CONTROL_ACC_SERIOUS', val: 1 },
    { col: 'CONTROL_CLUTCH_SERIOUS', val: 1 },
    { col: 'CONTROL_GEARS_SERIOUS', val: 1 },
    { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
    { col: 'CONTROL_PARK_SERIOUS', val: 0 },
    { col: 'CONTROL_STEERING_SERIOUS', val: 1 },
    { col: 'CONTROL_BALANCE_SERIOUS', val: 1 },
    { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 1 },
    { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 1 },
    { col: 'SIGNALS_NECESSARY_SERIOUS', val: 1 },
    { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 1 },
    { col: 'SIGNALS_TIMED_SERIOUS', val: 1 },
    { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 1 },
    { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 1 },
    { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 1 },
    { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 1 },
    { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 1 },
    { col: 'RESPONSE_OTHER_SERIOUS', val: 1 },
    { col: 'USE_OF_SPEED_SERIOUS', val: 1 },
    { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 1 },
    { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 1 },
    { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_SPEED_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 1 },
    { col: 'JUDGEMENT_OVER_SERIOUS', val: 1 },
    { col: 'JUDGEMENT_MEET_SERIOUS', val: 1 },
    { col: 'JUDGEMENT_CROSS_SERIOUS', val: 1 },
    { col: 'POSITIONING_NORMAL_SERIOUS', val: 1 },
    { col: 'POSITIONING_LANE_SERIOUS', val: 1 },
    { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 1 },
    { col: 'POSTITION_STOPS_SERIOUS', val: 1 },
    { col: 'AWARENESS_PLAN_SERIOUS', val: 1 },
    { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 1 },
    { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
    { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
    { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
    { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
    { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
    { col: 'CONTROL_BALANCE_DANGEROUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
    { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
    { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
    { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
    { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
    { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
    { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
    { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
    { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
    { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
    { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
    { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
    { col: 'EYESIGHT_SERIOUS', val: 1 },
    { col: 'EYESIGHT_COMPLETED', val: 1 },
    { col: 'VEHICLE_CHECKS_TOTAL', val: 2 },
    { col: 'VEHICLE_CHECKS_COMMENT', val: 'candidate fell off the bike' },
    { col: 'EYESIGHT_COMMENT', val: 'eyesight serious' },
    { col: 'PRECAUTIONS_COMMENT', val: 'precautions serious' },
    { col: 'CONTROL_ACC_COMMENT', val: 'controlsThrottle serious' },
    { col: 'CONTROL_CLUTCH_COMMENT', val: 'controlsClutch serious' },
    { col: 'CONTROL_GEARS_COMMENT', val: 'controlsGears serious' },
    { col: 'CONTROL_STEERING_COMMENT', val: 'controlsSteering serious' },
    { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'moveOffSafety serious' },
    { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'moveOffControl serious' },
    { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'useOfMirrorsSignalling serious' },
    { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'useOfMirrorsChangeDirection serious' },
    { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'useOfMirrorsChangeSpeed serious' },
    { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signalsNecessary serious' },
    { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signalsCorrectly serious' },
    { col: 'SIGNALS_TIMED_COMMENT', val: 'signalsTimed serious' },
    { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearanceOrObstructions serious' },
    { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'responseToSignsTrafficSigns serious' },
    { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'responseToSignsRoadMarkings serious' },
    { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'responseToSignsTrafficLights serious' },
    { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'responseToSignsTrafficControllers serious' },
    { col: 'RESPONSE_OTHER_COMMENT', val: 'responseToSignsOtherRoadUsers serious' },
    { col: 'USE_OF_SPEED_COMMENT', val: 'useOfSpeed serious' },
    { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'followingDistance serious' },
    { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progressAppropriateSpeed serious' },
    { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progressUndueHesitation serious' },
    { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctionsApproachSpeed serious' },
    { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctionsObservation serious' },
    { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctionsTurningRight serious' },
    { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctionsTurningLeft serious' },
    { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctionsCuttingCorners serious' },
    { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgementOvertaking serious' },
    { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgementMeeting serious' },
    { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgementCrossing serious' },
    { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioningNormalDriving serious' },
    { col: 'POSITIONING_LANE_COMMENT', val: 'positioningLaneDiscipline serious' },
    { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrianCrossings serious' },
    { col: 'POSITION_STOPS_COMMENT', val: 'positionNormalStops serious' },
    { col: 'AWARENESS_PLAN_COMMENT', val: 'awarenessPlanning serious' },
    { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillaryControls serious' },
    { col: 'INDEPENDENT_DRIVING', val: 'Traffic signs' },
    { col: 'SAFETY_1_CODE', val: 'SQ4' },
    { col: 'SAFETY_1_DESCRIPTION', val: 'Lights' },
    { col: 'SAFETY_2_CODE', val: 'SQ10' },
    { col: 'SAFETY_2_DESCRIPTION', val: 'Brakes' },
    { col: 'BALANCE_1_CODE', val: 'BQ3' },
    { col: 'BALANCE_1_DESCRIPTION', val: 'Balance with passenger' },
  ];
}

export function getFullyPopulatedDangerousDataFields(): DataField[] {
  return [
    { col: 'CONTROL_ACC_TOTAL', val: 0 },
    { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
    { col: 'CONTROL_GEARS_TOTAL', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
    { col: 'CONTROL_PARK_TOTAL', val: 0 },
    { col: 'CONTROL_STEERING_TOTAL', val: 0 },
    { col: 'CONTROL_BALANCE_TOTAL', val: 0 },
    { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
    { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
    { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
    { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
    { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
    { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
    { col: 'USE_OF_SPEED_TOTAL', val: 0 },
    { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
    { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
    { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
    { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
    { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
    { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
    { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
    { col: 'POSITIONING_LANE_TOTAL', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
    { col: 'POSTITION_STOPS_TOTAL', val: 0 },
    { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
    { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
    { col: 'CONTROL_ACC_SERIOUS', val: 0 },
    { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
    { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
    { col: 'CONTROL_PARK_SERIOUS', val: 0 },
    { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
    { col: 'CONTROL_BALANCE_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
    { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
    { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
    { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
    { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
    { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
    { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
    { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
    { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
    { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
    { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
    { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
    { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
    { col: 'CONTROL_ACC_DANGEROUS', val: 1 },
    { col: 'CONTROL_CLUTCH_DANGEROUS', val: 1 },
    { col: 'CONTROL_GEARS_DANGEROUS', val: 1 },
    { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
    { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
    { col: 'CONTROL_STEERING_DANGEROUS', val: 1 },
    { col: 'CONTROL_BALANCE_DANGEROUS', val: 1 },
    { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 1 },
    { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 1 },
    { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 1 },
    { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 1 },
    { col: 'SIGNALS_TIMED_DANGEROUS', val: 1 },
    { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 1 },
    { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 1 },
    { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 1 },
    { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 1 },
    { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 1 },
    { col: 'RESPONSE_OTHER_DANGEROUS', val: 1 },
    { col: 'USE_OF_SPEED_DANGEROUS', val: 1 },
    { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 1 },
    { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 1 },
    { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 1 },
    { col: 'JUDGEMENT_OVER_DANGEROUS', val: 1 },
    { col: 'JUDGEMENT_MEET_DANGEROUS', val: 1 },
    { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 1 },
    { col: 'POSITIONING_NORMAL_DANGEROUS', val: 1 },
    { col: 'POSITIONING_LANE_DANGEROUS', val: 1 },
    { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 1 },
    { col: 'POSTITION_STOPS_DANGEROUS', val: 1 },
    { col: 'AWARENESS_PLAN_DANGEROUS', val: 1 },
    { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 1 },
    { col: 'EYESIGHT_SERIOUS', val: 0 },
    { col: 'EYESIGHT_COMPLETED', val: 0 },
    { col: 'VEHICLE_CHECKS_TOTAL', val: 2 },
    { col: 'VEHICLE_CHECKS_COMMENT', val: 'candidate fell off the bike' },
    { col: 'PRECAUTIONS_COMMENT', val: 'precautions dangerous' },
    { col: 'CONTROL_ACC_COMMENT', val: 'controlsThrottle dangerous' },
    { col: 'CONTROL_CLUTCH_COMMENT', val: 'controlsClutch dangerous' },
    { col: 'CONTROL_GEARS_COMMENT', val: 'controlsGears dangerous' },
    { col: 'CONTROL_STEERING_COMMENT', val: 'controlsSteering dangerous' },
    { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'moveOffSafety dangerous' },
    { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'moveOffControl dangerous' },
    { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'useOfMirrorsSignalling dangerous' },
    { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'useOfMirrorsChangeDirection dangerous' },
    { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'useOfMirrorsChangeSpeed dangerous' },
    { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signalsNecessary dangerous' },
    { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signalsCorrectly dangerous' },
    { col: 'SIGNALS_TIMED_COMMENT', val: 'signalsTimed dangerous' },
    { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearanceOrObstructions dangerous' },
    { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'responseToSignsTrafficSigns dangerous' },
    { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'responseToSignsRoadMarkings dangerous' },
    { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'responseToSignsTrafficLights dangerous' },
    { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'responseToSignsTrafficControllers dangerous' },
    { col: 'RESPONSE_OTHER_COMMENT', val: 'responseToSignsOtherRoadUsers dangerous' },
    { col: 'USE_OF_SPEED_COMMENT', val: 'useOfSpeed dangerous' },
    { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'followingDistance dangerous' },
    { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progressAppropriateSpeed dangerous' },
    { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progressUndueHesitation dangerous' },
    { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctionsApproachSpeed dangerous' },
    { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctionsObservation dangerous' },
    { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctionsTurningRight dangerous' },
    { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctionsTurningLeft dangerous' },
    { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctionsCuttingCorners dangerous' },
    { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgementOvertaking dangerous' },
    { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgementMeeting dangerous' },
    { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgementCrossing dangerous' },
    { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioningNormalDriving dangerous' },
    { col: 'POSITIONING_LANE_COMMENT', val: 'positioningLaneDiscipline dangerous' },
    { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrianCrossings dangerous' },
    { col: 'POSITION_STOPS_COMMENT', val: 'positionNormalStops dangerous' },
    { col: 'AWARENESS_PLAN_COMMENT', val: 'awarenessPlanning dangerous' },
    { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillaryControls dangerous' },
    { col: 'INDEPENDENT_DRIVING', val: 'N/A' },
    { col: 'SAFETY_1_CODE', val: 'SQ4' },
    { col: 'SAFETY_1_DESCRIPTION', val: 'Lights' },
    { col: 'SAFETY_2_CODE', val: 'SQ10' },
    { col: 'SAFETY_2_DESCRIPTION', val: 'Brakes' },
    { col: 'BALANCE_1_CODE', val: 'BQ3' },
    { col: 'BALANCE_1_DESCRIPTION', val: 'Balance with passenger' },
  ];
}
