import { ResultUpload } from '../../../../../result-client';
import { SeverityText, IndependentDrivingText } from '../../enums/function-params';

export function getFullyPopulatedDrivingFaults(result: any): ResultUpload {
  return {
    ...result,
    testResult: {
      preTestDeclarations: {
        insuranceDeclarationAccepted: true,
        residencyDeclarationAccepted: true,
        preTestSignature: '**DUMMY**',
        DL196CBTCertNumber: '123456',
      },
      testData: {
        testRequirements: {
          normalStart1: true,
          normalStart2: true,
          angledStart: true,
          hillStart: true,
        },
        drivingFaults: {
          controlsThrottle: 1,
          controlsThrottleComments: 'controlsThrottleComments',
          controlsClutch: 2,
          controlsClutchComments: 'controlsClutchComments',
          controlsGears: 3,
          controlsGearsComments: 'controlsGearsComments',
          controlsFrontBrake: 4,
          controlsFrontBrakeComments: 'controlsFrontBrakeComments',
          controlsRearBrake: 5,
          controlsRearBrakeComments: 'controlsRearBrakeComments',
          controlsSteering: 6,
          controlsSteeringComments: 'controlsSteeringComments',
          controlsBalanceSlowControl: 7,
          controlsBalanceSlowControlComments: 'controlsBalanceSlowControlComments',
          ancillaryControls: 8,
          ancillaryControlsComments: 'ancillaryControlsComments',
          precautions: 9,
          precautionsComments: 'precautionsComments',
          moveOffSafety: 10,
          moveOffSafetyComments: 'moveOffSafetyComments',
          moveOffControl: 11,
          moveOffControlComments: 'moveOffControlComments',
          useOfMirrorsSignalling: 12,
          useOfMirrorsSignallingComments: 'useOfMirrorsSignallingComments',
          useOfMirrorsChangeDirection: 13,
          useOfMirrorsChangeDirectionComments: 'useOfMirrorsChangeDirectionComments',
          useOfMirrorsChangeSpeed: 14,
          useOfMirrorsChangeSpeedComments: 'useOfMirrorsChangeSpeedComments',
          signalsNecessary: 15,
          signalsNecessaryComments: 'signalsNecessaryComments',
          signalsCorrectly: 16,
          signalsCorrectlyComments: 'signalsCorrectlyComments',
          signalsTimed: 17,
          signalsTimedComments: 'signalsTimedComments',
          junctionsApproachSpeed: 18,
          junctionsApproachSpeedComments: 'junctionsApproachSpeedComments',
          junctionsObservation: 19,
          junctionsObservationComments: 'junctionsObservationComments',
          junctionsTurningRight: 20,
          junctionsTurningRightComments: 'junctionsTurningRightComments',
          junctionsTurningLeft: 21,
          junctionsTurningLeftComments: 'junctionsTurningLeftComments',
          junctionsCuttingCorners: 22,
          junctionsCuttingCornersComments: 'junctionsCuttingCornersComments',
          judgementOvertaking: 23,
          judgementOvertakingComments: 'judgementOvertakingComments',
          judgementMeeting: 24,
          judgementMeetingComments: 'judgementMeetingComments',
          judgementCrossing: 25,
          judgementCrossingComments: 'judgementCrossingComments',
          positioningNormalDriving: 26,
          positioningNormalDrivingComments: 'positioningNormalDrivingComments',
          positioningLaneDiscipline: 27,
          positioningLaneDisciplineComments: 'positioningLaneDisciplineComments',
          clearanceOrObstructions: 28,
          clearanceOrObstructionsComments: 'clearanceOrObstructionsComments',
          followingDistance: 29,
          followingDistanceComments: 'followingDistanceComments',
          useOfSpeed: 30,
          useOfSpeedComments: 'useOfSpeedComments',
          progressAppropriateSpeed: 31,
          progressAppropriateSpeedComments: 'progressAppropriateSpeedComments',
          progressUndueHesitation: 32,
          progressUndueHesitationComments: 'progressUndueHesitationComments',
          responseToSignsTrafficSigns: 33,
          responseToSignsTrafficSignsComments: 'responseToSignsTrafficSignsComments',
          responseToSignsRoadMarkings: 34,
          responseToSignsRoadMarkingsComments: 'responseToSignsRoadMarkingsComments',
          responseToSignsTrafficLights: 35,
          responseToSignsTrafficLightsComments: 'responseToSignsTrafficLightsComments',
          responseToSignsTrafficControllers: 36,
          responseToSignsTrafficControllersComments: 'responseToSignsTrafficControllersComments',
          responseToSignsOtherRoadUsers: 37,
          responseToSignsOtherRoadUsersComments: 'responseToSignsOtherRoadUsersComments',
          pedestrianCrossings: 38,
          pedestrianCrossingsComments: 'pedestrianCrossingsComments',
          positionNormalStops: 39,
          positionNormalStopsComments: 'positionNormalStopsComments',
          awarenessPlanning: 40,
          awarenessPlanningComments: 'awarenessPlanningComments',
          bends: 41,
          bendsComments: 'bendsComments',
        },
        safetyAndBalanceQuestions: {
          safetyQuestions: [
            {
              code: 'SQ4',
              description: 'Lights',
              outcome: 'DF',
            },
            {
              code: 'SQ10',
              description: 'Brakes',
              outcome: 'P',
            },
          ],
          balanceQuestions: [
            {
              code: 'BQ3',
              description: 'Balance with passenger',
              outcome: 'DF',
            },
          ],
          safetyAndBalanceComments: 'candidate fell off the bike',
        },
        eyesightTest: {
          complete: true,
        },
      },
      testSummary: getTestSummary(IndependentDrivingText.SatNav),
    },
  };
}

export function getFullyPopulatedSeriousFaults(result: any): ResultUpload {
  return {
    ...result,
    testResult: {
      preTestDeclarations: {
        insuranceDeclarationAccepted: true,
        residencyDeclarationAccepted: true,
        preTestSignature: '**DUMMY**',
        DL196CBTCertNumber: '123456',
      },
      testData: {
        testRequirements: {
          normalStart1: true,
          normalStart2: true,
          angledStart: true,
          hillStart: true,
        },
        seriousFaults: getFaultsByOutcomeSeverity(SeverityText.Serious),
        safetyAndBalanceQuestions: {
          safetyQuestions: [
            {
              code: 'SQ4',
              description: 'Lights',
              outcome: 'DF',
            },
            {
              code: 'SQ10',
              description: 'Brakes',
              outcome: 'P',
            },
          ],
          balanceQuestions: [
            {
              code: 'BQ3',
              description: 'Balance with passenger',
              outcome: 'DF',
            },
          ],
          safetyAndBalanceComments: 'candidate fell off the bike',
        },
        eyesightTest: getEyesightTestBySeverityOutcome(true, true, SeverityText.Serious),
      },
      testSummary: getTestSummary(IndependentDrivingText.TrafficSigns),
    },
  };
}

export function getFullyPopulatedDangerousFaults(result: any): ResultUpload {
  return {
    ...result,
    testResult: {
      preTestDeclarations: {
        insuranceDeclarationAccepted: true,
        residencyDeclarationAccepted: true,
        preTestSignature: '**DUMMY**',
        DL196CBTCertNumber: '123456',
      },
      testData: {
        testRequirements: {
          normalStart1: true,
          normalStart2: true,
          angledStart: true,
          hillStart: true,
        },
        dangerousFaults: getFaultsByOutcomeSeverity(SeverityText.Dangerous),
        safetyAndBalanceQuestions: {
          safetyQuestions: [
            {
              code: 'SQ4',
              description: 'Lights',
              outcome: 'DF',
            },
            {
              code: 'SQ10',
              description: 'Brakes',
              outcome: 'P',
            },
          ],
          balanceQuestions: [
            {
              code: 'BQ3',
              description: 'Balance with passenger',
              outcome: 'DF',
            },
          ],
          safetyAndBalanceComments: 'candidate fell off the bike',
        },
        eyesightTest: getEyesightTestBySeverityOutcome(false, false),
      },
      testSummary: getTestSummary(IndependentDrivingText.NotApplicable),
    },
  };
}

export function getFaultsByOutcomeSeverity(severityText: String) {
  return {
    controlsThrottle: 1,
    controlsThrottleComments: `controlsThrottle ${severityText}`,
    controlsClutch: 1,
    controlsClutchComments: `controlsClutch ${severityText}`,
    controlsGears: 1,
    controlsGearsComments: `controlsGears ${severityText}`,
    controlsFrontBrake: 1,
    controlsFrontBrakeComments: `controlsFrontBrake ${severityText}`,
    controlsRearBrake: 1,
    controlsRearBrakeComments: `controlsRearBrake ${severityText}`,
    controlsSteering: 1,
    controlsSteeringComments: `controlsSteering ${severityText}`,
    controlsBalanceSlowControl: 1,
    controlsBalanceSlowControlComments: `controlsBalanceSlowControl ${severityText}`,
    ancillaryControls: 1,
    ancillaryControlsComments: `ancillaryControls ${severityText}`,
    precautions: 1,
    precautionsComments: `precautions ${severityText}`,
    moveOffSafety: 1,
    moveOffSafetyComments: `moveOffSafety ${severityText}`,
    moveOffControl: 1,
    moveOffControlComments: `moveOffControl ${severityText}`,
    useOfMirrorsSignalling: 1,
    useOfMirrorsSignallingComments: `useOfMirrorsSignalling ${severityText}`,
    useOfMirrorsChangeDirection: 1,
    useOfMirrorsChangeDirectionComments: `useOfMirrorsChangeDirection ${severityText}`,
    useOfMirrorsChangeSpeed: 1,
    useOfMirrorsChangeSpeedComments: `useOfMirrorsChangeSpeed ${severityText}`,
    signalsNecessary: 1,
    signalsNecessaryComments: `signalsNecessary ${severityText}`,
    signalsCorrectly: 1,
    signalsCorrectlyComments: `signalsCorrectly ${severityText}`,
    signalsTimed: 1,
    signalsTimedComments: `signalsTimed ${severityText}`,
    junctionsApproachSpeed: 1,
    junctionsApproachSpeedComments: `junctionsApproachSpeed ${severityText}`,
    junctionsObservation: 1,
    junctionsObservationComments: `junctionsObservation ${severityText}`,
    junctionsTurningRight: 1,
    junctionsTurningRightComments: `junctionsTurningRight ${severityText}`,
    junctionsTurningLeft: 1,
    junctionsTurningLeftComments: `junctionsTurningLeft ${severityText}`,
    junctionsCuttingCorners: 1,
    junctionsCuttingCornersComments: `junctionsCuttingCorners ${severityText}`,
    judgementOvertaking: 1,
    judgementOvertakingComments: `judgementOvertaking ${severityText}`,
    judgementMeeting: 1,
    judgementMeetingComments: `judgementMeeting ${severityText}`,
    judgementCrossing: 1,
    judgementCrossingComments: `judgementCrossing ${severityText}`,
    positioningNormalDriving: 1,
    positioningNormalDrivingComments: `positioningNormalDriving ${severityText}`,
    positioningLaneDiscipline: 1,
    positioningLaneDisciplineComments: `positioningLaneDiscipline ${severityText}`,
    clearanceOrObstructions: 1,
    clearanceOrObstructionsComments: `clearanceOrObstructions ${severityText}`,
    followingDistance: 1,
    followingDistanceComments: `followingDistance ${severityText}`,
    useOfSpeed: 1,
    useOfSpeedComments: `useOfSpeed ${severityText}`,
    progressAppropriateSpeed: 1,
    progressAppropriateSpeedComments: `progressAppropriateSpeed ${severityText}`,
    progressUndueHesitation: 1,
    progressUndueHesitationComments: `progressUndueHesitation ${severityText}`,
    responseToSignsTrafficSigns: 1,
    responseToSignsTrafficSignsComments: `responseToSignsTrafficSigns ${severityText}`,
    responseToSignsRoadMarkings: 1,
    responseToSignsRoadMarkingsComments: `responseToSignsRoadMarkings ${severityText}`,
    responseToSignsTrafficLights: 1,
    responseToSignsTrafficLightsComments: `responseToSignsTrafficLights ${severityText}`,
    responseToSignsTrafficControllers: 1,
    responseToSignsTrafficControllersComments: `responseToSignsTrafficControllers ${severityText}`,
    responseToSignsOtherRoadUsers: 1,
    responseToSignsOtherRoadUsersComments: `responseToSignsOtherRoadUsers ${severityText}`,
    pedestrianCrossings: 1,
    pedestrianCrossingsComments: `pedestrianCrossings ${severityText}`,
    positionNormalStops: 1,
    positionNormalStopsComments: `positionNormalStops ${severityText}`,
    awarenessPlanning: 1,
    awarenessPlanningComments: `awarenessPlanning ${severityText}`,
    bends: 1,
    bendsComments: `bends ${severityText}`,
  };
}

export function getEyesightTestBySeverityOutcome(isComplete: boolean, isSerious: boolean, severityText: String = '') {
  return {
    complete: isComplete,
    seriousFault: isSerious,
    faultComments: isSerious ? `eyesight ${severityText}` : undefined,
  };
}

export function getTestSummary(independentDrivingText: String) {
  return {
    independentDriving: `${independentDrivingText}`,
  };
}
