import { DataField } from '../../../../../../domain/mi-export-data';

export function getCatDEFullyPopulatedSeriousDataFields(): DataField[] {
  return [
    { col: 'AUTOMATIC_TEST', val: 0 },
    { col: 'REV_LEFT_TRAIL_CONT_TOTAL', val: 0 },
    { col: 'REV_LEFT_TRAIL_OBSERV_TOTAL', val: 0 },
    { col: 'VEHICLE_CHECKS_TOTAL', val: 4 },
    { col: 'VEHICLE_CHECKS_SERIOUS', val: 1 },
    { col: 'PRECAUTIONS_TOTAL', val: 0 },
    { col: 'CONTROL_ACC_TOTAL', val: 0 },
    { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
    { col: 'CONTROL_GEARS_TOTAL', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
    { col: 'CONTROL_PARK_TOTAL', val: 0 },
    { col: 'CONTROL_STEERING_TOTAL', val: 0 },
    { col: 'CONTROL_PCV_DOOR_TOTAL', val: 0 },
    { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
    { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
    { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
    { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
    { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
    { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
    { col: 'USE_OF_SPEED_TOTAL', val: 0 },
    { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
    { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
    { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
    { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
    { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
    { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
    { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
    { col: 'POSITIONING_LANE_TOTAL', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
    { col: 'POSTITION_STOPS_TOTAL', val: 0 },
    { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
    { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
    { col: 'EYESIGHT_SERIOUS', val: 1 },
    { col: 'REV_LEFT_TRAIL_CONT_SERIOUS', val: 1 },
    { col: 'REV_LEFT_TRAIL_OBSERV_SERIOUS', val: 1 },
    { col: 'PRECAUTIONS_SERIOUS', val: 1 },
    { col: 'CONTROL_ACC_SERIOUS', val: 1 },
    { col: 'CONTROL_CLUTCH_SERIOUS', val: 1 },
    { col: 'CONTROL_GEARS_SERIOUS', val: 1 },
    { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 1 },
    { col: 'CONTROL_PARK_SERIOUS', val: 1 },
    { col: 'CONTROL_STEERING_SERIOUS', val: 1 },
    { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 1 },
    { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 1 },
    { col: 'SIGNALS_NECESSARY_SERIOUS', val: 1 },
    { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 1 },
    { col: 'SIGNALS_TIMED_SERIOUS', val: 1 },
    { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 1 },
    { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 1 },
    { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 1 },
    { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 1 },
    { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 1 },
    { col: 'RESPONSE_OTHER_SERIOUS', val: 1 },
    { col: 'USE_OF_SPEED_SERIOUS', val: 1 },
    { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 1 },
    { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 1 },
    { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_SPEED_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 1 },
    { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 1 },
    { col: 'JUDGEMENT_OVER_SERIOUS', val: 1 },
    { col: 'JUDGEMENT_MEET_SERIOUS', val: 1 },
    { col: 'JUDGEMENT_CROSS_SERIOUS', val: 1 },
    { col: 'POSITIONING_NORMAL_SERIOUS', val: 1 },
    { col: 'POSITIONING_LANE_SERIOUS', val: 1 },
    { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 1 },
    { col: 'POSTITION_STOPS_SERIOUS', val: 1 },
    { col: 'AWARENESS_PLAN_SERIOUS', val: 1 },
    { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 1 },
    { col: 'REV_LEFT_TRAIL_CONT_DANGEROUS', val: 0 },
    { col: 'REV_LEFT_TRAIL_OBSER_DANGEROUS', val: 0 },
    { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
    { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
    { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
    { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
    { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
    { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
    { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
    { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
    { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
    { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
    { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
    { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
    { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
    { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
    { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
    { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
    { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
    { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
    { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
    { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
    { col: 'EYESIGHT_COMPLETED', val: 1 },
    { col: 'REV_LEFT_TRAIL_COMPLETED', val: 1 },
    { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
    { col: 'NORMAL_STOP_1_COMPLETED', val: 1 },
    { col: 'NORMAL_STOP_2_COMPLETED', val: 1 },
    { col: 'ANGLED_START_COMPLETED', val: 1 },
    { col: 'UPHILL_START', val: 1 },
    { col: 'DOWN_HILL_START', val: 1 },
    { col: 'SAFETY_QUESTIONS_FIRE_EXTINGUISHER', val: 1 },
    { col: 'SAFETY_QUESTIONS_EMERGENCY_EXIT', val: 1 },
    { col: 'SAFETY_QUESTIONS_FUEL_CUTOFF', val: 1 },
    { col: 'EYESIGHT_COMMENT', val: 'eyesight serious' },
    { col: 'PRECAUTIONS_COMMENT', val: 'precautions serious' },
    { col: 'CONTROL_ACC_COMMENT', val: 'controls accelerator serious' },
    { col: 'CONTROL_CLUTCH_COMMENT', val: 'controls clutch serious' },
    { col: 'CONTROL_GEARS_COMMENT', val: 'controls gears serious' },
    { col: 'CONTROL_FOOTBRAKE_COMMENT', val: 'controls footbrake serious' },
    { col: 'CONTROL_PARK_COMMENT', val: 'controls parking brake serious' },
    { col: 'CONTROL_STEERING_COMMENT', val: 'controls steering serious' },
    { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'move off safety serious' },
    { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'move off control serious' },
    { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'use of mirrors signalling serious' },
    { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'use of mirrors change direction serious' },
    { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'use of mirrors change speed serious' },
    { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signals necessary serious' },
    { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signals correctly serious' },
    { col: 'SIGNALS_TIMED_COMMENT', val: 'signals timed serious' },
    { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearance serious' },
    { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'response to signs traffic signs serious' },
    { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'response to signs road markings serious' },
    { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'response to signs traffic lights serious' },
    { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'response to signs traffic controllers serious' },
    { col: 'RESPONSE_OTHER_COMMENT', val: 'response to signs other road users serious' },
    { col: 'USE_OF_SPEED_COMMENT', val: 'use of speed serious' },
    { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'following distance serious' },
    { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progress appropriate speed serious' },
    { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progress undue hesitation serious' },
    { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctions approach speed serious' },
    { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctions observation serious' },
    { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctions turning right serious' },
    { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctions turning left serious' },
    { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctions cutting corners serious' },
    { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgement overtaking serious' },
    { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgement meeting serious' },
    { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgement crossing serious' },
    { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioning normal driving serious' },
    { col: 'POSITIONING_LANE_COMMENT', val: 'positioning lane discipline serious' },
    { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrian crossings serious' },
    { col: 'POSITION_STOPS_COMMENT', val: 'position normal stops serious' },
    { col: 'AWARENESS_PLAN_COMMENT', val: 'awareness planning serious' },
    { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillary controls serious' },
    { col: 'REV_LEFT_TRAIL_CONT_COMMENT', val: 'reverse left control' },
    { col: 'REV_LEFT_TRAIL_OBSERV_COMMENT', val: 'reverse left observation' },
    { col: 'SHOW_ME_1_CODE', val: 'S1' },
    { col: 'SHOW_ME_1_DESCRIPTION', val: 'First Show Me Question' },
    { col: 'SHOW_ME_2_CODE', val: 'S2' },
    { col: 'SHOW_ME_2_DESCRIPTION', val: 'Second Show Me Question' },
    { col: 'SHOW_ME_3_CODE', val: 'S3' },
    { col: 'SHOW_ME_3_DESCRIPTION', val: 'Third Show Me Question' },
    { col: 'TELL_ME_1_CODE', val: 'T1' },
    { col: 'TELL_ME_1_DESCRIPTION', val: 'First Tell Me Question' },
    { col: 'TELL_ME_2_CODE', val: 'T2' },
    { col: 'TELL_ME_2_DESCRIPTION', val: 'Second Tell Me Question' },
    { col: 'VEHICLE_CHECKS_COMMENT', val: 'show me tell me serious' },
    { col: 'INDEPENDENT_DRIVING', val: 'Traffic signs' },
    { col: 'UNCOUPLE_RECOUPLE_TOTAL', val: 0 },
    { col: 'UNCOUPLE_RECOUPLE_SERIOUS', val: 0 },
    { col: 'UNCOUPLE_RECOUPLE_DANGEROUS', val: 0 },
    { col: 'UNCOUPLE_RECOUPLE_COMPLETED', val: 0 },
  ];
}

export function getCatDEFullyPopulatedDangerousDataFields(): DataField[] {
  return [
    { col: 'AUTOMATIC_TEST', val: 0 },
    { col: 'REV_LEFT_TRAIL_CONT_TOTAL', val: 0 },
    { col: 'REV_LEFT_TRAIL_OBSERV_TOTAL', val: 0 },
    { col: 'VEHICLE_CHECKS_TOTAL', val: 4 },
    { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
    { col: 'PRECAUTIONS_TOTAL', val: 0 },
    { col: 'CONTROL_ACC_TOTAL', val: 0 },
    { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
    { col: 'CONTROL_GEARS_TOTAL', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
    { col: 'CONTROL_PARK_TOTAL', val: 0 },
    { col: 'CONTROL_STEERING_TOTAL', val: 0 },
    { col: 'CONTROL_PCV_DOOR_TOTAL', val: 0 },
    { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
    { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
    { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
    { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
    { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
    { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
    { col: 'USE_OF_SPEED_TOTAL', val: 0 },
    { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
    { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
    { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
    { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
    { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
    { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
    { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
    { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
    { col: 'POSITIONING_LANE_TOTAL', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
    { col: 'POSTITION_STOPS_TOTAL', val: 0 },
    { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
    { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
    { col: 'EYESIGHT_SERIOUS', val: 0 },
    { col: 'REV_LEFT_TRAIL_CONT_SERIOUS', val: 0 },
    { col: 'REV_LEFT_TRAIL_OBSERV_SERIOUS', val: 0 },
    { col: 'PRECAUTIONS_SERIOUS', val: 0 },
    { col: 'CONTROL_ACC_SERIOUS', val: 0 },
    { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
    { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
    { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
    { col: 'CONTROL_PARK_SERIOUS', val: 0 },
    { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
    { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
    { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
    { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
    { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
    { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
    { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
    { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
    { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
    { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
    { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
    { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
    { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
    { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
    { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
    { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
    { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
    { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
    { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
    { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
    { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
    { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
    { col: 'REV_LEFT_TRAIL_CONT_DANGEROUS', val: 1 },
    { col: 'REV_LEFT_TRAIL_OBSER_DANGEROUS', val: 1 },
    { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
    { col: 'PRECAUTIONS_DANGEROUS', val: 1 },
    { col: 'CONTROL_ACC_DANGEROUS', val: 1 },
    { col: 'CONTROL_CLUTCH_DANGEROUS', val: 1 },
    { col: 'CONTROL_GEARS_DANGEROUS', val: 1 },
    { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 1 },
    { col: 'CONTROL_PARK_DANGEROUS', val: 1 },
    { col: 'CONTROL_STEERING_DANGEROUS', val: 1 },
    { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 1 },
    { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 1 },
    { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 1 },
    { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 1 },
    { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 1 },
    { col: 'SIGNALS_TIMED_DANGEROUS', val: 1 },
    { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 1 },
    { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 1 },
    { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 1 },
    { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 1 },
    { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 1 },
    { col: 'RESPONSE_OTHER_DANGEROUS', val: 1 },
    { col: 'USE_OF_SPEED_DANGEROUS', val: 1 },
    { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 1 },
    { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 1 },
    { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 1 },
    { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 1 },
    { col: 'JUDGEMENT_OVER_DANGEROUS', val: 1 },
    { col: 'JUDGEMENT_MEET_DANGEROUS', val: 1 },
    { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 1 },
    { col: 'POSITIONING_NORMAL_DANGEROUS', val: 1 },
    { col: 'POSITIONING_LANE_DANGEROUS', val: 1 },
    { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 1 },
    { col: 'POSTITION_STOPS_DANGEROUS', val: 1 },
    { col: 'AWARENESS_PLAN_DANGEROUS', val: 1 },
    { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 1 },
    { col: 'EYESIGHT_COMPLETED', val: 1 },
    { col: 'REV_LEFT_TRAIL_COMPLETED', val: 1 },
    { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
    { col: 'NORMAL_STOP_1_COMPLETED', val: 1 },
    { col: 'NORMAL_STOP_2_COMPLETED', val: 1 },
    { col: 'ANGLED_START_COMPLETED', val: 1 },
    { col: 'UPHILL_START', val: 1 },
    { col: 'DOWN_HILL_START', val: 1 },
    { col: 'SAFETY_QUESTIONS_FIRE_EXTINGUISHER', val: 1 },
    { col: 'SAFETY_QUESTIONS_EMERGENCY_EXIT', val: 1 },
    { col: 'SAFETY_QUESTIONS_FUEL_CUTOFF', val: 1 },
    { col: 'PRECAUTIONS_COMMENT', val: 'precautions dangerous' },
    { col: 'CONTROL_ACC_COMMENT', val: 'controls accelerator dangerous' },
    { col: 'CONTROL_CLUTCH_COMMENT', val: 'controls clutch dangerous' },
    { col: 'CONTROL_GEARS_COMMENT', val: 'controls gears dangerous' },
    { col: 'CONTROL_FOOTBRAKE_COMMENT', val: 'controls footbrake dangerous' },
    { col: 'CONTROL_PARK_COMMENT', val: 'controls parking brake dangerous' },
    { col: 'CONTROL_STEERING_COMMENT', val: 'controls steering dangerous' },
    { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'move off safety dangerous' },
    { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'move off control dangerous' },
    { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'use of mirrors signalling dangerous' },
    { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'use of mirrors change direction dangerous' },
    { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'use of mirrors change speed dangerous' },
    { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signals necessary dangerous' },
    { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signals correctly dangerous' },
    { col: 'SIGNALS_TIMED_COMMENT', val: 'signals timed dangerous' },
    { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearance dangerous' },
    { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'response to signs traffic signs dangerous' },
    { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'response to signs road markings dangerous' },
    { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'response to signs traffic lights dangerous' },
    { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'response to signs traffic controllers dangerous' },
    { col: 'RESPONSE_OTHER_COMMENT', val: 'response to signs other road users dangerous' },
    { col: 'USE_OF_SPEED_COMMENT', val: 'use of speed dangerous' },
    { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'following distance dangerous' },
    { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progress appropriate speed dangerous' },
    { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progress undue hesitation dangerous' },
    { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctions approach speed dangerous' },
    { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctions observation dangerous' },
    { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctions turning right dangerous' },
    { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctions turning left dangerous' },
    { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctions cutting corners dangerous' },
    { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgement overtaking dangerous' },
    { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgement meeting dangerous' },
    { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgement crossing dangerous' },
    { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioning normal driving dangerous' },
    { col: 'POSITIONING_LANE_COMMENT', val: 'positioning lane discipline dangerous' },
    { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrian crossings dangerous' },
    { col: 'POSITION_STOPS_COMMENT', val: 'position normal stops dangerous' },
    { col: 'AWARENESS_PLAN_COMMENT', val: 'awareness planning dangerous' },
    { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillary controls dangerous' },
    { col: 'REV_LEFT_TRAIL_CONT_COMMENT', val: 'reverse left control' },
    { col: 'REV_LEFT_TRAIL_OBSERV_COMMENT', val: 'reverse left observation' },
    { col: 'SHOW_ME_1_CODE', val: 'S1' },
    { col: 'SHOW_ME_1_DESCRIPTION', val: 'First Show Me Question' },
    { col: 'SHOW_ME_2_CODE', val: 'S2' },
    { col: 'SHOW_ME_2_DESCRIPTION', val: 'Second Show Me Question' },
    { col: 'SHOW_ME_3_CODE', val: 'S3' },
    { col: 'SHOW_ME_3_DESCRIPTION', val: 'Third Show Me Question' },
    { col: 'TELL_ME_1_CODE', val: 'T1' },
    { col: 'TELL_ME_1_DESCRIPTION', val: 'First Tell Me Question' },
    { col: 'TELL_ME_2_CODE', val: 'T2' },
    { col: 'TELL_ME_2_DESCRIPTION', val: 'Second Tell Me Question' },
    { col: 'INDEPENDENT_DRIVING', val: 'N/A' },
    { col: 'UNCOUPLE_RECOUPLE_TOTAL', val: 0 },
    { col: 'UNCOUPLE_RECOUPLE_SERIOUS', val: 0 },
    { col: 'UNCOUPLE_RECOUPLE_DANGEROUS', val: 0 },
    { col: 'UNCOUPLE_RECOUPLE_COMPLETED', val: 0 },
  ];
}
