import { cloneDeep } from 'lodash';
import { MissingTestResultDataError } from '../data-mapper';
import { DataField } from '../../../domain/mi-export-data';
import { InterfaceType, ResultUpload } from '../../result-client';
import { mapCatBData } from '../cat-b-mapper';

describe('mapCatBData', () => {

  it('Should map a minially populated test result (test terminated early as possible)', () => {
    const minimalInput: ResultUpload = {
      uploadKey: {
        applicationReference: 2222113,
        staffNumber: 1122,
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        category: 'B',
        id: 'TBC',
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleSlotType: 'B57mins',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '22',
      },
    };

    const expected: DataField[] = [
      { col: 'EYESIGHT_SERIOUS', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_TOTAL', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_TOTAL', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_TOTAL', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_TOTAL', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_TOTAL', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_TOTAL', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_TOTAL', val: 0 },
      { col: 'VEHICLE_CHECKS_TOTAL', val: 0 },
      { col: 'TAXI_MAN_CONTROL_TOTAL', val: 0 },
      { col: 'TAXI_MAN_OBSERV_TOTAL', val: 0 },
      { col: 'PRECAUTIONS_TOTAL', val: 0 },
      { col: 'CONTROL_ACC_TOTAL', val: 0 },
      { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
      { col: 'CONTROL_GEARS_TOTAL', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
      { col: 'CONTROL_PARK_TOTAL', val: 0 },
      { col: 'CONTROL_STEERING_TOTAL', val: 0 },
      { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
      { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
      { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
      { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
      { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
      { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
      { col: 'USE_OF_SPEED_TOTAL', val: 0 },
      { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
      { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
      { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
      { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
      { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
      { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
      { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
      { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
      { col: 'POSITIONING_LANE_TOTAL', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
      { col: 'POSTITION_STOPS_TOTAL', val: 0 },
      { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
      { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_SERIOUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_SERIOUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_SERIOUS', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_SERIOUS', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_SERIOUS', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_SERIOUS', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_SERIOUS', val: 0 },
      { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
      { col: 'TAXI_MAN_CONTROL_SERIOUS', val: 0 },
      { col: 'TAXI_MAN_OBSERV_SERIOUS', val: 0 },
      { col: 'PRECAUTIONS_SERIOUS', val: 0 },
      { col: 'CONTROL_ACC_SERIOUS', val: 0 },
      { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
      { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
      { col: 'CONTROL_PARK_SERIOUS', val: 0 },
      { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
      { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
      { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
      { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
      { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
      { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
      { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
      { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 0 },
      { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
      { col: 'TAXI_MAN_CONTROL_DANGEROUS', val: 0 },
      { col: 'TAXI_MAN_OBSERV_DANGEROUS', val: 0 },
      { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
      { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
      { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
      { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
      { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
      { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
      { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
      { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
      { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
      { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
      { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
      { col: 'CONTROL_STOP_COMPLETED', val: 0 },
      { col: 'REV_RIGHT_TRAIL_COMPLETED', val: 0 },
      { col: 'REVERSE_PARK_CARPARK', val: 0 },
      { col: 'REVERSE_PARK_ROAD', val: 0 },
      { col: 'VEHICLE_CHECKS_COMPLETED', val: 0 },
      { col: 'TAXI_MANOEUVRE_COMPLETED', val: 0 },
    ];

    // expect no faults, serious or dangerous...
    expect(mapCatBData(minimalInput)).toEqual(expected);
  });

  it('Should map a fully populated regular test result (every possible driving fault)', () => {
    const fullyPopulated: ResultUpload = {
      uploadKey: {
        applicationReference: 2222113,
        staffNumber: 1122,
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        category: 'B',
        id: 'TBC',
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleSlotType: 'B57mins',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '2',
        eyesightTestResult: 'F',
        testData: {
          vehicleChecks: {
            tellMeQuestion: {
              code: '1',
              outcome: 'DF',
            },
            showMeQuestion: {
              code: '2',
              outcome: 'DF',
            },
          },
          controlledStop: {
            selected: true,
            fault: 'DF',
          },
          manoeuvres: {
            reverseRight: {
              selected: true,
              controlFault: 'DF',
              observationFault: 'DF',
            },
            reverseParkCarpark: {
              selected: true,
              controlFault: 'DF',
              observationFault: 'DF',
            },
            reverseParkRoad: {
              selected: true,
              controlFault: 'DF',
              observationFault: 'DF',
            },
            forwardPark: {
              selected: true,
              controlFault: 'DF',
              observationFault: 'DF',
            },
          },
          drivingFaults: {
            precautions: 2,
            controlsAccelerator: 3,
            controlsClutch: 4,
            controlsGears: 5,
            controlsFootbrake: 6,
            controlsParkingBrake: 7,
            controlsSteering: 8,
            moveOffSafety: 9,
            moveOffControl: 10,
            useOfMirrorsSignalling: 11,
            useOfMirrorsChangeDirection: 12,
            useOfMirrorsChangeSpeed: 13,
            signalsNecessary: 14,
            signalsCorrectly: 15,
            signalsTimed: 16,
            clearance: 17,
            responseToSignsTrafficSigns: 18,
            responseToSignsRoadMarkings: 19,
            responseToSignsTrafficLights: 20,
            responseToSignsTrafficControllers: 21,
            responseToSignsOtherRoadUsers: 22,
            useOfSpeed: 23,
            followingDistance: 24,
            progressAppropriateSpeed: 25,
            progressUndueHesitation: 26,
            junctionsApproachSpeed: 27,
            junctionsObservation: 28,
            junctionsTurningRight: 29,
            junctionsTurningLeft: 30,
            junctionsCuttingCorners: 31,
            judgementOvertaking: 32,
            judgementMeeting: 33,
            judgementCrossing: 34,
            positioningNormalDriving: 35,
            positioningLaneDiscipline: 36,
            pedestrianCrossings: 37,
            positionNormalStops: 38,
            awarenessPlanning: 39,
            ancillaryControls: 40,
          },
        },
      },
    };

    const expected: DataField[] = [
      { col: 'EYESIGHT_SERIOUS', val: 1 },
      { col: 'CONTROL_STOP_PROMPT_TOTAL', val: 1 },
      { col: 'REV_RIGHT_TRAIL_CONT_TOTAL', val: 1 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_TOTAL', val: 1 },
      { col: 'REV_PARK_CPARK_CONTROL_TOTAL', val: 1 },
      { col: 'REV_PARK_CPARK_OBSERVE_TOTAL', val: 1 },
      { col: 'REV_PARK_ROAD_CONTROL_TOTAL', val: 1 },
      { col: 'REV_PARK_ROAD_OBSERVE_TOTAL', val: 1 },
      { col: 'VEHICLE_CHECKS_TOTAL', val: 1 },
      { col: 'TAXI_MAN_CONTROL_TOTAL', val: 1 },
      { col: 'TAXI_MAN_OBSERV_TOTAL', val: 1 },
      { col: 'PRECAUTIONS_TOTAL', val: 2 },
      { col: 'CONTROL_ACC_TOTAL', val: 3 },
      { col: 'CONTROL_CLUTCH_TOTAL', val: 4 },
      { col: 'CONTROL_GEARS_TOTAL', val: 5 },
      { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 6 },
      { col: 'CONTROL_PARK_TOTAL', val: 7 },
      { col: 'CONTROL_STEERING_TOTAL', val: 8 },
      { col: 'MOVE_OFF_SAFETY_TOTAL', val: 9 },
      { col: 'MOVE_OFF_CONTROL_TOTAL', val: 10 },
      { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 11 },
      { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 12 },
      { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 13 },
      { col: 'SIGNALS_NECESSARY_TOTAL', val: 14 },
      { col: 'SIGNALS_CORRECTLY_TOTAL', val: 15 },
      { col: 'SIGNALS_TIMED_TOTAL', val: 16 },
      { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 17 },
      { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 18 },
      { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 19 },
      { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 20 },
      { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 21 },
      { col: 'RESPONSE_OTHER_TOTAL', val: 22 },
      { col: 'USE_OF_SPEED_TOTAL', val: 23 },
      { col: 'FOLLOWING_DISTANCE_TOTAL', val: 24 },
      { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 25 },
      { col: 'MAINTAIN_PROG_HES_TOTAL', val: 26 },
      { col: 'JUNCTIONS_SPEED_TOTAL', val: 27 },
      { col: 'JUNCTIONS_OBSERV_TOTAL', val: 28 },
      { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 29 },
      { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 30 },
      { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 31 },
      { col: 'JUDGEMENT_OVER_TOTAL', val: 32 },
      { col: 'JUDGEMENT_MEET_TOTAL', val: 33 },
      { col: 'JUDGEMENT_CROSS_TOTAL', val: 34 },
      { col: 'POSITIONING_NORMAL_TOTAL', val: 35 },
      { col: 'POSITIONING_LANE_TOTAL', val: 36 },
      { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 37 },
      { col: 'POSTITION_STOPS_TOTAL', val: 38 },
      { col: 'AWARENESS_PLAN_TOTAL', val: 39 },
      { col: 'ANCILLARY_CONTROLS_TOTAL', val: 40 },
      { col: 'CONTROL_STOP_PROMPT_SERIOUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_SERIOUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_SERIOUS', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_SERIOUS', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_SERIOUS', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_SERIOUS', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_SERIOUS', val: 0 },
      { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
      { col: 'TAXI_MAN_CONTROL_SERIOUS', val: 0 },
      { col: 'TAXI_MAN_OBSERV_SERIOUS', val: 0 },
      { col: 'PRECAUTIONS_SERIOUS', val: 0 },
      { col: 'CONTROL_ACC_SERIOUS', val: 0 },
      { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
      { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
      { col: 'CONTROL_PARK_SERIOUS', val: 0 },
      { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
      { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
      { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
      { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
      { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
      { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
      { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
      { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 0 },
      { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
      { col: 'TAXI_MAN_CONTROL_DANGEROUS', val: 0 },
      { col: 'TAXI_MAN_OBSERV_DANGEROUS', val: 0 },
      { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
      { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
      { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
      { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
      { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
      { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
      { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
      { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
      { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
      { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
      { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
      { col: 'CONTROL_STOP_COMPLETED', val: 1 },
      { col: 'REV_RIGHT_TRAIL_COMPLETED', val: 1 },
      { col: 'REVERSE_PARK_CARPARK', val: 1 },
      { col: 'REVERSE_PARK_ROAD', val: 1 },
      { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
      { col: 'TAXI_MANOEUVRE_COMPLETED', val: 1 },
    ];

    // expect the right number of faults, with no serious or dangerous
    expect(mapCatBData(fullyPopulated)).toEqual(expected);
  });

  it('Should map a fully populated regular test result (every possible serious fault)', () => {
    const fullyPopulated: ResultUpload = {
      uploadKey: {
        applicationReference: 2222113,
        staffNumber: 1122,
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        category: 'B',
        id: 'TBC',
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleSlotType: 'B57mins',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '2',
        eyesightTestResult: 'F',
        testData: {
          vehicleChecks: {
            tellMeQuestion: {
              code: '1',
              outcome: 'S',
            },
            showMeQuestion: {
              code: '2',
              outcome: 'S',
            },
          },
          controlledStop: {
            selected: true,
            fault: 'S',
          },
          manoeuvres: {
            reverseRight: {
              selected: true,
              controlFault: 'S',
              observationFault: 'S',
            },
            reverseParkRoad: {
              selected: true,
              controlFault: 'S',
              observationFault: 'S',
            },
            reverseParkCarpark: {
              selected: true,
              controlFault: 'S',
              observationFault: 'S',
            },
            forwardPark: {
              selected: true,
              controlFault: 'S',
              observationFault: 'S',
            },
          },
          seriousFaults: {
            precautions: true,
            controlsAccelerator: true,
            controlsClutch: true,
            controlsGears: true,
            controlsFootbrake: true,
            controlsParkingBrake: true,
            controlsSteering: true,
            moveOffSafety: true,
            moveOffControl: true,
            useOfMirrorsSignalling: true,
            useOfMirrorsChangeDirection: true,
            useOfMirrorsChangeSpeed: true,
            signalsNecessary: true,
            signalsCorrectly: true,
            signalsTimed: true,
            clearance: true,
            responseToSignsTrafficSigns: true,
            responseToSignsRoadMarkings: true,
            responseToSignsTrafficLights: true,
            responseToSignsTrafficControllers: true,
            responseToSignsOtherRoadUsers: true,
            useOfSpeed: true,
            followingDistance: true,
            progressAppropriateSpeed: true,
            progressUndueHesitation: true,
            junctionsApproachSpeed: true,
            junctionsObservation: true,
            junctionsTurningRight: true,
            junctionsTurningLeft: true,
            junctionsCuttingCorners: true,
            judgementOvertaking: true,
            judgementMeeting: true,
            judgementCrossing: true,
            positioningNormalDriving: true,
            positioningLaneDiscipline: true,
            pedestrianCrossings: true,
            positionNormalStops: true,
            awarenessPlanning: true,
            ancillaryControls: true,
          },
        },
      },
    };

    const expected: DataField[] = [
      { col: 'EYESIGHT_SERIOUS', val: 1 },
      { col: 'CONTROL_STOP_PROMPT_TOTAL', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_TOTAL', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_TOTAL', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_TOTAL', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_TOTAL', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_TOTAL', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_TOTAL', val: 0 },
      { col: 'VEHICLE_CHECKS_TOTAL', val: 0 },
      { col: 'TAXI_MAN_CONTROL_TOTAL', val: 0 },
      { col: 'TAXI_MAN_OBSERV_TOTAL', val: 0 },
      { col: 'PRECAUTIONS_TOTAL', val: 0 },
      { col: 'CONTROL_ACC_TOTAL', val: 0 },
      { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
      { col: 'CONTROL_GEARS_TOTAL', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
      { col: 'CONTROL_PARK_TOTAL', val: 0 },
      { col: 'CONTROL_STEERING_TOTAL', val: 0 },
      { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
      { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
      { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
      { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
      { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
      { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
      { col: 'USE_OF_SPEED_TOTAL', val: 0 },
      { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
      { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
      { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
      { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
      { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
      { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
      { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
      { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
      { col: 'POSITIONING_LANE_TOTAL', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
      { col: 'POSTITION_STOPS_TOTAL', val: 0 },
      { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
      { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_SERIOUS', val: 1 },
      { col: 'REV_RIGHT_TRAIL_CONT_SERIOUS', val: 1 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_SERIOUS', val: 1 },
      { col: 'REV_PARK_CPARK_CONTROL_SERIOUS', val: 1 },
      { col: 'REV_PARK_CPARK_OBSERVE_SERIOUS', val: 1 },
      { col: 'REV_PARK_ROAD_CONTROL_SERIOUS', val: 1 },
      { col: 'REV_PARK_ROAD_OBSERVE_SERIOUS', val: 1 },
      { col: 'VEHICLE_CHECKS_SERIOUS', val: 1 },
      { col: 'TAXI_MAN_CONTROL_SERIOUS', val: 1 },
      { col: 'TAXI_MAN_OBSERV_SERIOUS', val: 1 },
      { col: 'PRECAUTIONS_SERIOUS', val: 1 },
      { col: 'CONTROL_ACC_SERIOUS', val: 1 },
      { col: 'CONTROL_CLUTCH_SERIOUS', val: 1 },
      { col: 'CONTROL_GEARS_SERIOUS', val: 1 },
      { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 1 },
      { col: 'CONTROL_PARK_SERIOUS', val: 1 },
      { col: 'CONTROL_STEERING_SERIOUS', val: 1 },
      { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 1 },
      { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 1 },
      { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 1 },
      { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 1 },
      { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 1 },
      { col: 'SIGNALS_NECESSARY_SERIOUS', val: 1 },
      { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 1 },
      { col: 'SIGNALS_TIMED_SERIOUS', val: 1 },
      { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 1 },
      { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 1 },
      { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 1 },
      { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 1 },
      { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 1 },
      { col: 'RESPONSE_OTHER_SERIOUS', val: 1 },
      { col: 'USE_OF_SPEED_SERIOUS', val: 1 },
      { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 1 },
      { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 1 },
      { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 1 },
      { col: 'JUNCTIONS_SPEED_SERIOUS', val: 1 },
      { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 1 },
      { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 1 },
      { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 1 },
      { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 1 },
      { col: 'JUDGEMENT_OVER_SERIOUS', val: 1 },
      { col: 'JUDGEMENT_MEET_SERIOUS', val: 1 },
      { col: 'JUDGEMENT_CROSS_SERIOUS', val: 1 },
      { col: 'POSITIONING_NORMAL_SERIOUS', val: 1 },
      { col: 'POSITIONING_LANE_SERIOUS', val: 1 },
      { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 1 },
      { col: 'POSTITION_STOPS_SERIOUS', val: 1 },
      { col: 'AWARENESS_PLAN_SERIOUS', val: 1 },
      { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 1 },
      { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 0 },
      { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
      { col: 'TAXI_MAN_CONTROL_DANGEROUS', val: 0 },
      { col: 'TAXI_MAN_OBSERV_DANGEROUS', val: 0 },
      { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
      { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
      { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
      { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
      { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
      { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
      { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
      { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
      { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
      { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
      { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
      { col: 'CONTROL_STOP_COMPLETED', val: 1 },
      { col: 'REV_RIGHT_TRAIL_COMPLETED', val: 1 },
      { col: 'REVERSE_PARK_CARPARK', val: 1 },
      { col: 'REVERSE_PARK_ROAD', val: 1 },
      { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
      { col: 'TAXI_MANOEUVRE_COMPLETED', val: 1 },
    ];

    // expect all serious, no faults or dangerous
    expect(mapCatBData(fullyPopulated)).toEqual(expected);
  });

  it('Should map a fully populated regular test result (every possible dangerous fault)', () => {
    const fullyPopulated: ResultUpload = {
      uploadKey: {
        applicationReference: 2222113,
        staffNumber: 1122,
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        category: 'B',
        id: 'TBC',
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleSlotType: 'B57mins',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '2',
        eyesightTestResult: 'F',
        testData: {
          vehicleChecks: {
            tellMeQuestion: {
              code: '1',
              outcome: 'D',
            },
            showMeQuestion: {
              code: '2',
              outcome: 'D',
            },
          },
          controlledStop: {
            selected: true,
            fault: 'D',
          },
          manoeuvres: {
            reverseRight: {
              selected: true,
              controlFault: 'D',
              observationFault: 'D',
            },
            reverseParkRoad: {
              selected: true,
              controlFault: 'D',
              observationFault: 'D',
            },
            reverseParkCarpark: {
              selected: true,
              controlFault: 'D',
              observationFault: 'D',
            },
            forwardPark: {
              selected: true,
              controlFault: 'D',
              observationFault: 'D',
            },
          },
          dangerousFaults: {
            precautions: true,
            controlsAccelerator: true,
            controlsClutch: true,
            controlsGears: true,
            controlsFootbrake: true,
            controlsParkingBrake: true,
            controlsSteering: true,
            moveOffSafety: true,
            moveOffControl: true,
            useOfMirrorsSignalling: true,
            useOfMirrorsChangeDirection: true,
            useOfMirrorsChangeSpeed: true,
            signalsNecessary: true,
            signalsCorrectly: true,
            signalsTimed: true,
            clearance: true,
            responseToSignsTrafficSigns: true,
            responseToSignsRoadMarkings: true,
            responseToSignsTrafficLights: true,
            responseToSignsTrafficControllers: true,
            responseToSignsOtherRoadUsers: true,
            useOfSpeed: true,
            followingDistance: true,
            progressAppropriateSpeed: true,
            progressUndueHesitation: true,
            junctionsApproachSpeed: true,
            junctionsObservation: true,
            junctionsTurningRight: true,
            junctionsTurningLeft: true,
            junctionsCuttingCorners: true,
            judgementOvertaking: true,
            judgementMeeting: true,
            judgementCrossing: true,
            positioningNormalDriving: true,
            positioningLaneDiscipline: true,
            pedestrianCrossings: true,
            positionNormalStops: true,
            awarenessPlanning: true,
            ancillaryControls: true,
          },
        },
      },
    };

    const expected: DataField[] = [
      { col: 'EYESIGHT_SERIOUS', val: 1 },
      { col: 'CONTROL_STOP_PROMPT_TOTAL', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_TOTAL', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_TOTAL', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_TOTAL', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_TOTAL', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_TOTAL', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_TOTAL', val: 0 },
      { col: 'VEHICLE_CHECKS_TOTAL', val: 0 },
      { col: 'TAXI_MAN_CONTROL_TOTAL', val: 0 },
      { col: 'TAXI_MAN_OBSERV_TOTAL', val: 0 },
      { col: 'PRECAUTIONS_TOTAL', val: 0 },
      { col: 'CONTROL_ACC_TOTAL', val: 0 },
      { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
      { col: 'CONTROL_GEARS_TOTAL', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
      { col: 'CONTROL_PARK_TOTAL', val: 0 },
      { col: 'CONTROL_STEERING_TOTAL', val: 0 },
      { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
      { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
      { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
      { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
      { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
      { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
      { col: 'USE_OF_SPEED_TOTAL', val: 0 },
      { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
      { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
      { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
      { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
      { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
      { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
      { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
      { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
      { col: 'POSITIONING_LANE_TOTAL', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
      { col: 'POSTITION_STOPS_TOTAL', val: 0 },
      { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
      { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_SERIOUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_CONT_SERIOUS', val: 0 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_SERIOUS', val: 0 },
      { col: 'REV_PARK_CPARK_CONTROL_SERIOUS', val: 0 },
      { col: 'REV_PARK_CPARK_OBSERVE_SERIOUS', val: 0 },
      { col: 'REV_PARK_ROAD_CONTROL_SERIOUS', val: 0 },
      { col: 'REV_PARK_ROAD_OBSERVE_SERIOUS', val: 0 },
      { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
      { col: 'TAXI_MAN_CONTROL_SERIOUS', val: 0 },
      { col: 'TAXI_MAN_OBSERV_SERIOUS', val: 0 },
      { col: 'PRECAUTIONS_SERIOUS', val: 0 },
      { col: 'CONTROL_ACC_SERIOUS', val: 0 },
      { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
      { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
      { col: 'CONTROL_PARK_SERIOUS', val: 0 },
      { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
      { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
      { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
      { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
      { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
      { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
      { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
      { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
      { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 1 },
      { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 1 },
      { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 1 },
      { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 1 },
      { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 1 },
      { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 1 },
      { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 1 },
      { col: 'VEHICLE_CHECKS_DANGEROUS', val: 1 },
      { col: 'TAXI_MAN_CONTROL_DANGEROUS', val: 1 },
      { col: 'TAXI_MAN_OBSERV_DANGEROUS', val: 1 },
      { col: 'PRECAUTIONS_DANGEROUS', val: 1 },
      { col: 'CONTROL_ACC_DANGEROUS', val: 1 },
      { col: 'CONTROL_CLUTCH_DANGEROUS', val: 1 },
      { col: 'CONTROL_GEARS_DANGEROUS', val: 1 },
      { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 1 },
      { col: 'CONTROL_PARK_DANGEROUS', val: 1 },
      { col: 'CONTROL_STEERING_DANGEROUS', val: 1 },
      { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 1 },
      { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 1 },
      { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 1 },
      { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 1 },
      { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 1 },
      { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 1 },
      { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 1 },
      { col: 'SIGNALS_TIMED_DANGEROUS', val: 1 },
      { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 1 },
      { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 1 },
      { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 1 },
      { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 1 },
      { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 1 },
      { col: 'RESPONSE_OTHER_DANGEROUS', val: 1 },
      { col: 'USE_OF_SPEED_DANGEROUS', val: 1 },
      { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 1 },
      { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 1 },
      { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 1 },
      { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 1 },
      { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 1 },
      { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 1 },
      { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 1 },
      { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 1 },
      { col: 'JUDGEMENT_OVER_DANGEROUS', val: 1 },
      { col: 'JUDGEMENT_MEET_DANGEROUS', val: 1 },
      { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 1 },
      { col: 'POSITIONING_NORMAL_DANGEROUS', val: 1 },
      { col: 'POSITIONING_LANE_DANGEROUS', val: 1 },
      { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 1 },
      { col: 'POSTITION_STOPS_DANGEROUS', val: 1 },
      { col: 'AWARENESS_PLAN_DANGEROUS', val: 1 },
      { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 1 },
      { col: 'CONTROL_STOP_COMPLETED', val: 1 },
      { col: 'REV_RIGHT_TRAIL_COMPLETED', val: 1 },
      { col: 'REVERSE_PARK_CARPARK', val: 1 },
      { col: 'REVERSE_PARK_ROAD', val: 1 },
      { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
      { col: 'TAXI_MANOEUVRE_COMPLETED', val: 1 },
    ];

    // expect all dangerous, no faults or serious
    expect(mapCatBData(fullyPopulated)).toEqual(expected);
  });
});
