import { DataField } from '../../../domain/mi-export-data';
import { InterfaceType, ResultUpload } from '../../result-client';
import { mapCatBEData } from '../cat-be-mapper';

describe('mapCatBEData', () => {

  it('Should map a minially populated test result (test terminated early as possible)', () => {
    const minimalInput: ResultUpload = {
      uploadKey: {
        applicationReference: {
          applicationId: 2222,
          bookingSequence: 11,
          checkDigit: 3,
        },
        staffNumber: '1122',
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        version: '0.0.1',
        category: 'B+E',
        rekey: false,
        changeMarker: false,
        examinerBooked: 12345678,
        examinerConducted: 12345678,
        examinerKeyed: 12345678,
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleTypeCode: 'C',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '22',
      },
      autosaved: 0, // false
    };

    const expected: DataField[] = [
        { col: 'REV_LEFT_TRAIL_CONT_TOTAL', val: 0 },
        { col: 'REV_LEFT_TRAIL_OBSERV_TOTAL', val: 0 },
        { col: 'VEHICLE_CHECKS_TOTAL', val: 0 },
        { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_TOTAL', val: 0 },
        { col: 'PRECAUTIONS_TOTAL', val: 0 },
        { col: 'CONTROL_ACC_TOTAL', val: 0 },
        { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
        { col: 'CONTROL_GEARS_TOTAL', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
        { col: 'CONTROL_PARK_TOTAL', val: 0 },
        { col: 'CONTROL_STEERING_TOTAL', val: 0 },
        { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
        { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
        { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
        { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
        { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
        { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
        { col: 'USE_OF_SPEED_TOTAL', val: 0 },
        { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
        { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
        { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
        { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
        { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
        { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
        { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
        { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
        { col: 'POSITIONING_LANE_TOTAL', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
        { col: 'POSTITION_STOPS_TOTAL', val: 0 },
        { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
        { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
        { col: 'EYESIGHT_SERIOUS', val: 0 },
        { col: 'REV_LEFT_TRAIL_CONT_SERIOUS', val: 0 },
        { col: 'REV_LEFT_TRAIL_OBSERV_SERIOUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_SERIOUS', val: 0 },
        { col: 'PRECAUTIONS_SERIOUS' , val: 0 },
        { col: 'CONTROL_ACC_SERIOUS', val: 0 },
        { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
        { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
        { col: 'CONTROL_PARK_SERIOUS', val: 0 },
        { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
        { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
        { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
        { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
        { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
        { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
        { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
        { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
        { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
        { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
        { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
        { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
        { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
        { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
        { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
        { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
        { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
        { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
        { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_DANGEROUS', val: 0 },
        { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
        { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
        { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
        { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
        { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
        { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
        { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
        { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
        { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
        { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
        { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
        { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
        { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
        { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
        { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
        { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
        { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
        { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
        { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
        { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
        { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
        { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
        { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
        { col: 'EYESIGHT_COMPLETED', val: 0 },
        { col: 'REV_LEFT_TRAIL_COMPLETED', val: 0 },
        { col: 'VEHICLE_CHECKS_COMPLETED', val: 0 },
        { col: 'NORMAL_STOP_1_COMPLETED', val: 0 },
        { col: 'NORMAL_STOP_2_COMPLETED', val: 0 },
        { col: 'ANGLED_START_COMPLETED', val: 0 },
        { col: 'UPHILL_START', val: 0 },
        { col: 'DOWN_HILL_START', val: 0 },
    ];
    const result = mapCatBEData(minimalInput);
    // expect no faults, serious or dangerous...
    expect(result).toEqual(expected);
  });

  it('Should map a fully populated regular test result (every possible driving fault)', () => {
    const fullyPopulated: ResultUpload = {
      uploadKey: {
        applicationReference: {
          applicationId: 2222,
          bookingSequence: 11,
          checkDigit: 3,
        },
        staffNumber: '1122',
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        version: '0.0.1',
        category: 'B+E',
        rekey: false,
        changeMarker: false,
        examinerBooked: 12345678,
        examinerConducted: 12345678,
        examinerKeyed: 12345678,
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleTypeCode: 'C',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '2',
        testData: {
          testRequirements: {
            normalStart1: true,
            normalStart2: true,
            angledStartControlledStop: true,
            uphillStart: true,
            downhillStart: true,
          },
          vehicleChecks: {
            tellMeQuestions: [
              {
                code: 'T1',
                description: 'First Tell Me Question',
                outcome: 'DF',
              },
              {
                code: 'T2',
                description: 'Second Tell Me Question',
                outcome: 'P',
              },
            ],
            showMeQuestions: [
              {
                code: 'S1',
                description: 'First Show Me Question',
                outcome: 'DF',
              },
              {
                code: 'S2',
                description: 'Second Show Me Question',
                outcome: 'DF',
              },
              {
                code: 'S3',
                description: 'Third Show Me Question',
                outcome: 'DF',
              },
            ],
            showMeTellMeComments: 'show me tell me fault',
          },
          uncoupleRecouple: {
            selected: true,
            fault: 'DF',
            faultComments: 'uncouple recouple',
          },
          manoeuvres: {
            reverseLeft: {
              selected: true,
              controlFault: 'DF',
              controlFaultComments: 'reverse left control',
              observationFault: 'DF',
              observationFaultComments: 'reverse left observation',
            },
          },
          drivingFaults: {
            precautions: 2,
            precautionsComments: 'precautions fault',
            controlsAccelerator: 3,
            controlsAcceleratorComments: 'controls accelerator fault',
            controlsClutch: 4,
            controlsClutchComments: 'controls clutch fault',
            controlsGears: 5,
            controlsGearsComments: 'controls gears fault',
            controlsFootbrake: 6,
            controlsFootbrakeComments: 'controls footbrake fault',
            controlsParkingBrake: 7,
            controlsParkingBrakeComments: 'controls parking brake fault',
            controlsSteering: 8,
            controlsSteeringComments: 'controls steering fault',
            moveOffSafety: 9,
            moveOffSafetyComments: 'move off safety fault',
            moveOffControl: 10,
            moveOffControlComments: 'move off control fault',
            useOfMirrorsSignalling: 11,
            useOfMirrorsSignallingComments: 'use of mirrors signalling fault',
            useOfMirrorsChangeDirection: 12,
            useOfMirrorsChangeDirectionComments: 'use of mirrors change direction fault',
            useOfMirrorsChangeSpeed: 13,
            useOfMirrorsChangeSpeedComments: 'use of mirrors change speed fault',
            signalsNecessary: 14,
            signalsNecessaryComments: 'signals necessary fault',
            signalsCorrectly: 15,
            signalsCorrectlyComments: 'signals correctly fault',
            signalsTimed: 16,
            signalsTimedComments: 'signals timed fault',
            clearance: 17,
            clearanceComments: 'clearance fault',
            responseToSignsTrafficSigns: 18,
            responseToSignsTrafficSignsComments: 'response to signs traffic signs fault',
            responseToSignsRoadMarkings: 19,
            responseToSignsRoadMarkingsComments: 'response to signs road markings fault',
            responseToSignsTrafficLights: 20,
            responseToSignsTrafficLightsComments: 'response to signs traffic lights fault',
            responseToSignsTrafficControllers: 21,
            responseToSignsTrafficControllersComments: 'response to signs traffic controllers fault',
            responseToSignsOtherRoadUsers: 22,
            responseToSignsOtherRoadUsersComments: 'response to signs other road users fault',
            useOfSpeed: 23,
            useOfSpeedComments: 'use of speed fault',
            followingDistance: 24,
            followingDistanceComments: 'following distance fault',
            progressAppropriateSpeed: 25,
            progressAppropriateSpeedComments: 'progress appropriate speed fault',
            progressUndueHesitation: 26,
            progressUndueHesitationComments: 'progress undue hesitation fault',
            junctionsApproachSpeed: 27,
            junctionsApproachSpeedComments: 'junctions approach speed fault',
            junctionsObservation: 28,
            junctionsObservationComments: 'junctions observation fault',
            junctionsTurningRight: 29,
            junctionsTurningRightComments: 'junctions turning right fault',
            junctionsTurningLeft: 30,
            junctionsTurningLeftComments: 'junctions turning left fault',
            junctionsCuttingCorners: 31,
            junctionsCuttingCornersComments: 'junctions cutting corners fault',
            judgementOvertaking: 32,
            judgementOvertakingComments: 'judgement overtaking fault',
            judgementMeeting: 33,
            judgementMeetingComments: 'judgement meeting fault',
            judgementCrossing: 34,
            judgementCrossingComments: 'judgement crossing fault',
            positioningNormalDriving: 35,
            positioningNormalDrivingComments: 'positioning normal driving fault',
            positioningLaneDiscipline: 36,
            positioningLaneDisciplineComments: 'positioning lane discipline fault',
            pedestrianCrossings: 37,
            pedestrianCrossingsComments: 'pedestrian crossings fault',
            positionNormalStops: 38,
            positionNormalStopsComments: 'position normal stops fault',
            awarenessPlanning: 39,
            awarenessPlanningComments: 'awareness planning fault',
            ancillaryControls: 40,
            ancillaryControlsComments: 'ancillary controls fault',
          },
          eyesightTest: {
            complete: true,
          },
        },
        testSummary: {
          independentDriving: 'Sat nav',
        },
      },
      autosaved: 0, // false
    };

    const expected: DataField[] = [
      { col: 'REV_LEFT_TRAIL_CONT_TOTAL', val: 1 },
      { col: 'REV_LEFT_TRAIL_OBSERV_TOTAL', val: 1 },
      { col: 'VEHICLE_CHECKS_TOTAL', val: 4 },
      { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
      { col: 'UNCOUPLE_RECOUPLE_TOTAL', val: 1 },
      { col: 'PRECAUTIONS_TOTAL', val: 2 },
      { col: 'CONTROL_ACC_TOTAL', val: 3 },
      { col: 'CONTROL_CLUTCH_TOTAL', val: 4 },
      { col: 'CONTROL_GEARS_TOTAL', val: 5 },
      { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 6 },
      { col: 'CONTROL_PARK_TOTAL', val: 7 },
      { col: 'CONTROL_STEERING_TOTAL', val: 8 },
      { col: 'MOVE_OFF_SAFETY_TOTAL', val: 9 },
      { col: 'MOVE_OFF_CONTROL_TOTAL', val: 10 },
      { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 11 },
      { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 12 },
      { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 13 },
      { col: 'SIGNALS_NECESSARY_TOTAL', val: 14 },
      { col: 'SIGNALS_CORRECTLY_TOTAL', val: 15 },
      { col: 'SIGNALS_TIMED_TOTAL', val: 16 },
      { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 17 },
      { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 18 },
      { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 19 },
      { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 20 },
      { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 21 },
      { col: 'RESPONSE_OTHER_TOTAL', val: 22 },
      { col: 'USE_OF_SPEED_TOTAL', val: 23 },
      { col: 'FOLLOWING_DISTANCE_TOTAL', val: 24 },
      { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 25 },
      { col: 'MAINTAIN_PROG_HES_TOTAL', val: 26 },
      { col: 'JUNCTIONS_SPEED_TOTAL', val: 27 },
      { col: 'JUNCTIONS_OBSERV_TOTAL', val: 28 },
      { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 29 },
      { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 30 },
      { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 31 },
      { col: 'JUDGEMENT_OVER_TOTAL', val: 32 },
      { col: 'JUDGEMENT_MEET_TOTAL', val: 33 },
      { col: 'JUDGEMENT_CROSS_TOTAL', val: 34 },
      { col: 'POSITIONING_NORMAL_TOTAL', val: 35 },
      { col: 'POSITIONING_LANE_TOTAL', val: 36 },
      { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 37 },
      { col: 'POSTITION_STOPS_TOTAL', val: 38 },
      { col: 'AWARENESS_PLAN_TOTAL', val: 39 },
      { col: 'ANCILLARY_CONTROLS_TOTAL', val: 40 },
      { col: 'EYESIGHT_SERIOUS', val: 0 },
      { col: 'REV_LEFT_TRAIL_CONT_SERIOUS', val: 0 },
      { col: 'REV_LEFT_TRAIL_OBSERV_SERIOUS', val: 0 },
      { col: 'UNCOUPLE_RECOUPLE_SERIOUS', val: 0 },
      { col: 'PRECAUTIONS_SERIOUS', val: 0 },
      { col: 'CONTROL_ACC_SERIOUS', val: 0 },
      { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
      { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
      { col: 'CONTROL_PARK_SERIOUS', val: 0 },
      { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
      { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
      { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
      { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
      { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
      { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
      { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
      { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
    //   { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
    //   { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 0 },
    //   { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 0 },
    //   { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 0 },
    //   { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 0 },
    //   { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 0 },
    //   { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 0 },
      { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
      { col: 'UNCOUPLE_RECOUPLE_DANGEROUS', val: 0 },
      { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
      { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
      { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
      { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
      { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
      { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
      { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
      { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
      { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
      { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
      { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
      { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
      { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
      { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
      { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
      { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
      { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
      { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
      { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
      { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
      { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
      { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
      { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
      { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
      { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
      { col: 'EYESIGHT_COMPLETED', val: 1 },
      { col: 'REV_LEFT_TRAIL_COMPLETED', val: 1 },
      { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
      { col: 'NORMAL_STOP_1_COMPLETED', val: 1 },
      { col: 'NORMAL_STOP_2_COMPLETED', val: 1 },
      { col: 'ANGLED_START_COMPLETED', val: 1 },
      { col: 'UPHILL_START', val: 1 },
      { col: 'DOWN_HILL_START', val: 1 },
      { col: 'PRECAUTIONS_COMMENT', val: 'precautions fault' },
      { col: 'CONTROL_ACC_COMMENT', val: 'controls accelerator fault' },
      { col: 'CONTROL_CLUTCH_COMMENT', val: 'controls clutch fault' },
      { col: 'CONTROL_GEARS_COMMENT', val: 'controls gears fault' },
      { col: 'CONTROL_FOOTBRAKE_COMMENT', val: 'controls footbrake fault' },
      { col: 'CONTROL_PARK_COMMENT', val: 'controls parking brake fault' },
      { col: 'CONTROL_STEERING_COMMENT', val: 'controls steering fault' },
      { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'move off safety fault' },
      { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'move off control fault' },
      { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'use of mirrors signalling fault' },
      { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'use of mirrors change direction fault' },
      { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'use of mirrors change speed fault' },
      { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signals necessary fault' },
      { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signals correctly fault' },
      { col: 'SIGNALS_TIMED_COMMENT', val: 'signals timed fault' },
      { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearance fault' },
      { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'response to signs traffic signs fault' },
      { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'response to signs road markings fault' },
      { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'response to signs traffic lights fault' },
      { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'response to signs traffic controllers fault' },
      { col: 'RESPONSE_OTHER_COMMENT', val: 'response to signs other road users fault' },
      { col: 'USE_OF_SPEED_COMMENT', val: 'use of speed fault' },
      { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'following distance fault' },
      { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progress appropriate speed fault' },
      { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progress undue hesitation fault' },
      { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctions approach speed fault' },
      { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctions observation fault' },
      { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctions turning right fault' },
      { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctions turning left fault' },
      { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctions cutting corners fault' },
      { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgement overtaking fault' },
      { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgement meeting fault' },
      { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgement crossing fault' },
      { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioning normal driving fault' },
      { col: 'POSITIONING_LANE_COMMENT', val: 'positioning lane discipline fault' },
      { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrian crossings fault' },
      { col: 'POSITION_STOPS_COMMENT', val: 'position normal stops fault' },
      { col: 'AWARENESS_PLAN_COMMENT', val: 'awareness planning fault' },
      { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillary controls fault' },
    //   { col: 'SHOW_ME_1_CODE', val: 'S2' },
    //   { col: 'SHOW_ME_1_DESCRIPTION', val: 'Second Show Me Question' },
    //   { col: 'TELL_ME_1_CODE', val: 'T1' },
    //   { col: 'TELL_ME_1_DESCRIPTION', val: 'First Tell Me Question' },
      { col: 'VEHICLE_CHECKS_COMMENT', val: 'show me tell me fault' },
      { col: 'INDEPENDENT_DRIVING', val: 'Sat nav' },
    ];

    // expect the right number of faults, with no serious or dangerous
    const result = mapCatBEData(fullyPopulated);
    expect(result).toEqual(expected);
  });

  it('Should map a fully populated regular test result (every possible serious fault)', () => {
    const fullyPopulated: ResultUpload = {
      uploadKey: {
        applicationReference: {
          applicationId: 2222,
          bookingSequence: 11,
          checkDigit: 3,
        },
        staffNumber: '1122',
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        version: '0.0.1',
        category: 'B+E',
        rekey: false,
        changeMarker: false,
        examinerBooked: 12345678,
        examinerConducted: 12345678,
        examinerKeyed: 12345678,
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleTypeCode: 'C',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '2',
        testData: {
          testRequirements: {
            normalStart1: true,
            normalStart2: true,
            angledStartControlledStop: true,
            uphillStart: true,
            downhillStart: true,
          },
          vehicleChecks: {
            tellMeQuestions: [
              {
                code: 'T1',
                description: 'First Tell Me Question',
                outcome: 'DF',
              },
              {
                code: 'T2',
                description: 'Second Tell Me Question',
                outcome: 'DF',
              },
            ],
            showMeQuestions: [
              {
                code: 'S1',
                description: 'First Show Me Question',
                outcome: 'DF',
              },
              {
                code: 'S2',
                description: 'Second Show Me Question',
                outcome: 'DF',
              },
              {
                code: 'S3',
                description: 'Third Show Me Question',
                outcome: 'DF',
              },
            ],
            showMeTellMeComments: 'show me tell me serious',
          },
          uncoupleRecouple: {
            selected: true,
            fault: 'S',
            faultComments: 'uncouple recouple',
          },
          manoeuvres: {
            reverseLeft: {
              selected: true,
              controlFault: 'S',
              controlFaultComments: 'reverse left control',
              observationFault: 'S',
              observationFaultComments: 'reverse left observation',
            },
          },
          seriousFaults: {
            precautions: true,
            precautionsComments: 'precautions serious',
            controlsAccelerator: true,
            controlsAcceleratorComments: 'controls accelerator serious',
            controlsClutch: true,
            controlsClutchComments: 'controls clutch serious',
            controlsGears: true,
            controlsGearsComments: 'controls gears serious',
            controlsFootbrake: true,
            controlsFootbrakeComments: 'controls footbrake serious',
            controlsParkingBrake: true,
            controlsParkingBrakeComments: 'controls parking brake serious',
            controlsSteering: true,
            controlsSteeringComments: 'controls steering serious',
            moveOffSafety: true,
            moveOffSafetyComments: 'move off safety serious',
            moveOffControl: true,
            moveOffControlComments: 'move off control serious',
            useOfMirrorsSignalling: true,
            useOfMirrorsSignallingComments: 'use of mirrors signalling serious',
            useOfMirrorsChangeDirection: true,
            useOfMirrorsChangeDirectionComments: 'use of mirrors change direction serious',
            useOfMirrorsChangeSpeed: true,
            useOfMirrorsChangeSpeedComments: 'use of mirrors change speed serious',
            signalsNecessary: true,
            signalsNecessaryComments: 'signals necessary serious',
            signalsCorrectly: true,
            signalsCorrectlyComments: 'signals correctly serious',
            signalsTimed: true,
            signalsTimedComments: 'signals timed serious',
            clearance: true,
            clearanceComments: 'clearance serious',
            responseToSignsTrafficSigns: true,
            responseToSignsTrafficSignsComments: 'response to signs traffic signs serious',
            responseToSignsRoadMarkings: true,
            responseToSignsRoadMarkingsComments: 'response to signs road markings serious',
            responseToSignsTrafficLights: true,
            responseToSignsTrafficLightsComments: 'response to signs traffic lights serious',
            responseToSignsTrafficControllers: true,
            responseToSignsTrafficControllersComments: 'response to signs traffic controllers serious',
            responseToSignsOtherRoadUsers: true,
            responseToSignsOtherRoadUsersComments: 'response to signs other road users serious',
            useOfSpeed: true,
            useOfSpeedComments: 'use of speed serious',
            followingDistance: true,
            followingDistanceComments: 'following distance serious',
            progressAppropriateSpeed: true,
            progressAppropriateSpeedComments: 'progress appropriate speed serious',
            progressUndueHesitation: true,
            progressUndueHesitationComments: 'progress undue hesitation serious',
            junctionsApproachSpeed: true,
            junctionsApproachSpeedComments: 'junctions approach speed serious',
            junctionsObservation: true,
            junctionsObservationComments: 'junctions observation serious',
            junctionsTurningRight: true,
            junctionsTurningRightComments: 'junctions turning right serious',
            junctionsTurningLeft: true,
            junctionsTurningLeftComments: 'junctions turning left serious',
            junctionsCuttingCorners: true,
            junctionsCuttingCornersComments: 'junctions cutting corners serious',
            judgementOvertaking: true,
            judgementOvertakingComments: 'judgement overtaking serious',
            judgementMeeting: true,
            judgementMeetingComments: 'judgement meeting serious',
            judgementCrossing: true,
            judgementCrossingComments: 'judgement crossing serious',
            positioningNormalDriving: true,
            positioningNormalDrivingComments: 'positioning normal driving serious',
            positioningLaneDiscipline: true,
            positioningLaneDisciplineComments: 'positioning lane discipline serious',
            pedestrianCrossings: true,
            pedestrianCrossingsComments: 'pedestrian crossings serious',
            positionNormalStops: true,
            positionNormalStopsComments: 'position normal stops serious',
            awarenessPlanning: true,
            awarenessPlanningComments: 'awareness planning serious',
            ancillaryControls: true,
            ancillaryControlsComments: 'ancillary controls serious',
          },
          eyesightTest: {
            complete: true,
            seriousFault: true,
            faultComments: 'eyesight serious',
          },
        },
        testSummary: {
          independentDriving: 'Traffic signs',
        },
      },
      autosaved: 0, // false
    };

    const expected: DataField[] = [
        { col: 'REV_LEFT_TRAIL_CONT_TOTAL', val: 0 },
        { col: 'REV_LEFT_TRAIL_OBSERV_TOTAL', val: 0 },
        { col: 'VEHICLE_CHECKS_TOTAL', val: 4 },
        { col: 'VEHICLE_CHECKS_SERIOUS', val: 1 },
        { col: 'UNCOUPLE_RECOUPLE_TOTAL', val: 0 },
        { col: 'PRECAUTIONS_TOTAL', val: 0 },
        { col: 'CONTROL_ACC_TOTAL', val: 0 },
        { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
        { col: 'CONTROL_GEARS_TOTAL', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
        { col: 'CONTROL_PARK_TOTAL', val: 0 },
        { col: 'CONTROL_STEERING_TOTAL', val: 0 },
        { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
        { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
        { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
        { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
        { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
        { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
        { col: 'USE_OF_SPEED_TOTAL', val: 0 },
        { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
        { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
        { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
        { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
        { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
        { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
        { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
        { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
        { col: 'POSITIONING_LANE_TOTAL', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
        { col: 'POSTITION_STOPS_TOTAL', val: 0 },
        { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
        { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
        { col: 'EYESIGHT_SERIOUS', val: 1 },
        { col: 'REV_LEFT_TRAIL_CONT_SERIOUS', val: 1 },
        { col: 'REV_LEFT_TRAIL_OBSERV_SERIOUS', val: 1 },
        { col: 'UNCOUPLE_RECOUPLE_SERIOUS', val: 1 },
        { col: 'PRECAUTIONS_SERIOUS', val: 1 },
        { col: 'CONTROL_ACC_SERIOUS', val: 1 },
        { col: 'CONTROL_CLUTCH_SERIOUS', val: 1 },
        { col: 'CONTROL_GEARS_SERIOUS', val: 1 },
        { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 1 },
        { col: 'CONTROL_PARK_SERIOUS', val: 1 },
        { col: 'CONTROL_STEERING_SERIOUS', val: 1 },
        { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 1 },
        { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 1 },
        { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 1 },
        { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 1 },
        { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 1 },
        { col: 'SIGNALS_NECESSARY_SERIOUS', val: 1 },
        { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 1 },
        { col: 'SIGNALS_TIMED_SERIOUS', val: 1 },
        { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 1 },
        { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 1 },
        { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 1 },
        { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 1 },
        { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 1 },
        { col: 'RESPONSE_OTHER_SERIOUS', val: 1 },
        { col: 'USE_OF_SPEED_SERIOUS', val: 1 },
        { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 1 },
        { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 1 },
        { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 1 },
        { col: 'JUNCTIONS_SPEED_SERIOUS', val: 1 },
        { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 1 },
        { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 1 },
        { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 1 },
        { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 1 },
        { col: 'JUDGEMENT_OVER_SERIOUS', val: 1 },
        { col: 'JUDGEMENT_MEET_SERIOUS', val: 1 },
        { col: 'JUDGEMENT_CROSS_SERIOUS', val: 1 },
        { col: 'POSITIONING_NORMAL_SERIOUS', val: 1 },
        { col: 'POSITIONING_LANE_SERIOUS', val: 1 },
        { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 1 },
        { col: 'POSTITION_STOPS_SERIOUS', val: 1 },
        { col: 'AWARENESS_PLAN_SERIOUS', val: 1 },
        { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 1 },
      //   { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
      //   { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 0 },
      //   { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 0 },
      //   { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 0 },
      //   { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 0 },
      //   { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 0 },
      //   { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 0 },
        { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_DANGEROUS', val: 0 },
        { col: 'PRECAUTIONS_DANGEROUS', val: 0 },
        { col: 'CONTROL_ACC_DANGEROUS', val: 0 },
        { col: 'CONTROL_CLUTCH_DANGEROUS', val: 0 },
        { col: 'CONTROL_GEARS_DANGEROUS', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 0 },
        { col: 'CONTROL_PARK_DANGEROUS', val: 0 },
        { col: 'CONTROL_STEERING_DANGEROUS', val: 0 },
        { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 0 },
        { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 0 },
        { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 0 },
        { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 0 },
        { col: 'SIGNALS_TIMED_DANGEROUS', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 0 },
        { col: 'RESPONSE_OTHER_DANGEROUS', val: 0 },
        { col: 'USE_OF_SPEED_DANGEROUS', val: 0 },
        { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 0 },
        { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 0 },
        { col: 'JUDGEMENT_OVER_DANGEROUS', val: 0 },
        { col: 'JUDGEMENT_MEET_DANGEROUS', val: 0 },
        { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 0 },
        { col: 'POSITIONING_NORMAL_DANGEROUS', val: 0 },
        { col: 'POSITIONING_LANE_DANGEROUS', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 0 },
        { col: 'POSTITION_STOPS_DANGEROUS', val: 0 },
        { col: 'AWARENESS_PLAN_DANGEROUS', val: 0 },
        { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 0 },
        { col: 'EYESIGHT_COMPLETED', val: 1 },
        { col: 'REV_LEFT_TRAIL_COMPLETED', val: 1 },
        { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
        { col: 'NORMAL_STOP_1_COMPLETED', val: 1 },
        { col: 'NORMAL_STOP_2_COMPLETED', val: 1 },
        { col: 'ANGLED_START_COMPLETED', val: 1 },
        { col: 'UPHILL_START', val: 1 },
        { col: 'DOWN_HILL_START', val: 1 },
        { col: 'EYESIGHT_COMMENT', val: 'eyesight serious' },
        { col: 'PRECAUTIONS_COMMENT', val: 'precautions serious' },
        { col: 'CONTROL_ACC_COMMENT', val: 'controls accelerator serious' },
        { col: 'CONTROL_CLUTCH_COMMENT', val: 'controls clutch serious' },
        { col: 'CONTROL_GEARS_COMMENT', val: 'controls gears serious' },
        { col: 'CONTROL_FOOTBRAKE_COMMENT', val: 'controls footbrake serious' },
        { col: 'CONTROL_PARK_COMMENT', val: 'controls parking brake serious' },
        { col: 'CONTROL_STEERING_COMMENT', val: 'controls steering serious' },
        { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'move off safety serious' },
        { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'move off control serious' },
        { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'use of mirrors signalling serious' },
        { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'use of mirrors change direction serious' },
        { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'use of mirrors change speed serious' },
        { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signals necessary serious' },
        { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signals correctly serious' },
        { col: 'SIGNALS_TIMED_COMMENT', val: 'signals timed serious' },
        { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearance serious' },
        { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'response to signs traffic signs serious' },
        { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'response to signs road markings serious' },
        { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'response to signs traffic lights serious' },
        { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'response to signs traffic controllers serious' },
        { col: 'RESPONSE_OTHER_COMMENT', val: 'response to signs other road users serious' },
        { col: 'USE_OF_SPEED_COMMENT', val: 'use of speed serious' },
        { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'following distance serious' },
        { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progress appropriate speed serious' },
        { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progress undue hesitation serious' },
        { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctions approach speed serious' },
        { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctions observation serious' },
        { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctions turning right serious' },
        { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctions turning left serious' },
        { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctions cutting corners serious' },
        { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgement overtaking serious' },
        { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgement meeting serious' },
        { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgement crossing serious' },
        { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioning normal driving serious' },
        { col: 'POSITIONING_LANE_COMMENT', val: 'positioning lane discipline serious' },
        { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrian crossings serious' },
        { col: 'POSITION_STOPS_COMMENT', val: 'position normal stops serious' },
        { col: 'AWARENESS_PLAN_COMMENT', val: 'awareness planning serious' },
        { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillary controls serious' },
      //   { col: 'SHOW_ME_1_CODE', val: 'S2' },
      //   { col: 'SHOW_ME_1_DESCRIPTION', val: 'Second Show Me Question' },
      //   { col: 'TELL_ME_1_CODE', val: 'T1' },
      //   { col: 'TELL_ME_1_DESCRIPTION', val: 'First Tell Me Question' },
        { col: 'VEHICLE_CHECKS_COMMENT', val: 'show me tell me serious' },
        { col: 'INDEPENDENT_DRIVING', val: 'Traffic signs' },
    ];

    // expect all serious, no faults or dangerous
    expect(mapCatBEData(fullyPopulated)).toEqual(expected);
  });

  it('Should map a fully populated regular test result (every possible dangerous fault)', () => {
    const fullyPopulated: ResultUpload = {
      uploadKey: {
        applicationReference: {
          applicationId: 2222,
          bookingSequence: 11,
          checkDigit: 3,
        },
        staffNumber: '1122',
        interfaceType: InterfaceType.RSIS,
      },
      testResult: {
        version: '0.0.1',
        category: 'B+E',
        rekey: false,
        changeMarker: false,
        examinerBooked: 12345678,
        examinerConducted: 12345678,
        examinerKeyed: 12345678,
        journalData: {
          examiner: {
            staffNumber: '001122',
          },
          testCentre: {
            centreId: 1234,
            costCode: 'CC1',
          },
          testSlotAttributes: {
            slotId: 1234,
            start: '2019-06-10T09:30:00',
            vehicleTypeCode: 'C',
            welshTest: false,
            specialNeeds: false,
            extendedTest: false,
          },
          candidate: { },
          applicationReference: {
            applicationId: 2222,
            bookingSequence: 11,
            checkDigit: 3,
          },
        },
        activityCode: '2',
        testData: {
          testRequirements: {
            normalStart1: true,
            normalStart2: true,
            angledStartControlledStop: true,
            uphillStart: true,
            downhillStart: true,
          },
          vehicleChecks: {
            tellMeQuestions: [
              {
                code: 'T1',
                description: 'First Tell Me Question',
                outcome: 'DF',
              },
              {
                code: 'T2',
                description: 'Second Tell Me Question',
                outcome: 'DF',
              },
            ],
            showMeQuestions: [
              {
                code: 'S1',
                description: 'First Show Me Question',
                outcome: 'DF',
              },
              {
                code: 'S2',
                description: 'Second Show Me Question',
                outcome: 'DF',
              },
              {
                code: 'S3',
                description: 'Third Show Me Question',
                outcome: 'P',
              },
            ],
          },
          uncoupleRecouple: {
            selected: true,
            fault: 'D',
            faultComments: 'uncouple recouple',
          },
          manoeuvres: {
            reverseLeft: {
              selected: true,
              controlFault: 'D',
              controlFaultComments: 'reverse left control',
              observationFault: 'D',
              observationFaultComments: 'reverse left observation',
            },
          },
          dangerousFaults: {
            precautions: true,
            precautionsComments: 'precautions dangerous',
            controlsAccelerator: true,
            controlsAcceleratorComments: 'controls accelerator dangerous',
            controlsClutch: true,
            controlsClutchComments: 'controls clutch dangerous',
            controlsGears: true,
            controlsGearsComments: 'controls gears dangerous',
            controlsFootbrake: true,
            controlsFootbrakeComments: 'controls footbrake dangerous',
            controlsParkingBrake: true,
            controlsParkingBrakeComments: 'controls parking brake dangerous',
            controlsSteering: true,
            controlsSteeringComments: 'controls steering dangerous',
            moveOffSafety: true,
            moveOffSafetyComments: 'move off safety dangerous',
            moveOffControl: true,
            moveOffControlComments: 'move off control dangerous',
            useOfMirrorsSignalling: true,
            useOfMirrorsSignallingComments: 'use of mirrors signalling dangerous',
            useOfMirrorsChangeDirection: true,
            useOfMirrorsChangeDirectionComments: 'use of mirrors change direction dangerous',
            useOfMirrorsChangeSpeed: true,
            useOfMirrorsChangeSpeedComments: 'use of mirrors change speed dangerous',
            signalsNecessary: true,
            signalsNecessaryComments: 'signals necessary dangerous',
            signalsCorrectly: true,
            signalsCorrectlyComments: 'signals correctly dangerous',
            signalsTimed: true,
            signalsTimedComments: 'signals timed dangerous',
            clearance: true,
            clearanceComments: 'clearance dangerous',
            responseToSignsTrafficSigns: true,
            responseToSignsTrafficSignsComments: 'response to signs traffic signs dangerous',
            responseToSignsRoadMarkings: true,
            responseToSignsRoadMarkingsComments: 'response to signs road markings dangerous',
            responseToSignsTrafficLights: true,
            responseToSignsTrafficLightsComments: 'response to signs traffic lights dangerous',
            responseToSignsTrafficControllers: true,
            responseToSignsTrafficControllersComments: 'response to signs traffic controllers dangerous',
            responseToSignsOtherRoadUsers: true,
            responseToSignsOtherRoadUsersComments: 'response to signs other road users dangerous',
            useOfSpeed: true,
            useOfSpeedComments: 'use of speed dangerous',
            followingDistance: true,
            followingDistanceComments: 'following distance dangerous',
            progressAppropriateSpeed: true,
            progressAppropriateSpeedComments: 'progress appropriate speed dangerous',
            progressUndueHesitation: true,
            progressUndueHesitationComments: 'progress undue hesitation dangerous',
            junctionsApproachSpeed: true,
            junctionsApproachSpeedComments: 'junctions approach speed dangerous',
            junctionsObservation: true,
            junctionsObservationComments: 'junctions observation dangerous',
            junctionsTurningRight: true,
            junctionsTurningRightComments: 'junctions turning right dangerous',
            junctionsTurningLeft: true,
            junctionsTurningLeftComments: 'junctions turning left dangerous',
            junctionsCuttingCorners: true,
            junctionsCuttingCornersComments: 'junctions cutting corners dangerous',
            judgementOvertaking: true,
            judgementOvertakingComments: 'judgement overtaking dangerous',
            judgementMeeting: true,
            judgementMeetingComments: 'judgement meeting dangerous',
            judgementCrossing: true,
            judgementCrossingComments: 'judgement crossing dangerous',
            positioningNormalDriving: true,
            positioningNormalDrivingComments: 'positioning normal driving dangerous',
            positioningLaneDiscipline: true,
            positioningLaneDisciplineComments: 'positioning lane discipline dangerous',
            pedestrianCrossings: true,
            pedestrianCrossingsComments: 'pedestrian crossings dangerous',
            positionNormalStops: true,
            positionNormalStopsComments: 'position normal stops dangerous',
            awarenessPlanning: true,
            awarenessPlanningComments: 'awareness planning dangerous',
            ancillaryControls: true,
            ancillaryControlsComments: 'ancillary controls dangerous',
          },
          eyesightTest: {
            complete: true,
            seriousFault: false,
          },
        },
        testSummary: {
          independentDriving: 'N/A',
        },
      },
      autosaved: 0, // false
    };

    const expected: DataField[] = [
        { col: 'REV_LEFT_TRAIL_CONT_TOTAL', val: 0 },
        { col: 'REV_LEFT_TRAIL_OBSERV_TOTAL', val: 0 },
        { col: 'VEHICLE_CHECKS_TOTAL', val: 4 },
        { col: 'VEHICLE_CHECKS_SERIOUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_TOTAL', val: 0 },
        { col: 'PRECAUTIONS_TOTAL', val: 0 },
        { col: 'CONTROL_ACC_TOTAL', val: 0 },
        { col: 'CONTROL_CLUTCH_TOTAL', val: 0 },
        { col: 'CONTROL_GEARS_TOTAL', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_TOTAL', val: 0 },
        { col: 'CONTROL_PARK_TOTAL', val: 0 },
        { col: 'CONTROL_STEERING_TOTAL', val: 0 },
        { col: 'MOVE_OFF_SAFETY_TOTAL', val: 0 },
        { col: 'MOVE_OFF_CONTROL_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_TOTAL', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_TOTAL', val: 0 },
        { col: 'SIGNALS_NECESSARY_TOTAL', val: 0 },
        { col: 'SIGNALS_CORRECTLY_TOTAL', val: 0 },
        { col: 'SIGNALS_TIMED_TOTAL', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_TOTAL', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_TOTAL', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_TOTAL', val: 0 },
        { col: 'RESPONSE_OTHER_TOTAL', val: 0 },
        { col: 'USE_OF_SPEED_TOTAL', val: 0 },
        { col: 'FOLLOWING_DISTANCE_TOTAL', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_TOTAL', val: 0 },
        { col: 'MAINTAIN_PROG_HES_TOTAL', val: 0 },
        { col: 'JUNCTIONS_SPEED_TOTAL', val: 0 },
        { col: 'JUNCTIONS_OBSERV_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_TOTAL', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_TOTAL', val: 0 },
        { col: 'JUDGEMENT_OVER_TOTAL', val: 0 },
        { col: 'JUDGEMENT_MEET_TOTAL', val: 0 },
        { col: 'JUDGEMENT_CROSS_TOTAL', val: 0 },
        { col: 'POSITIONING_NORMAL_TOTAL', val: 0 },
        { col: 'POSITIONING_LANE_TOTAL', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_TOTAL', val: 0 },
        { col: 'POSTITION_STOPS_TOTAL', val: 0 },
        { col: 'AWARENESS_PLAN_TOTAL', val: 0 },
        { col: 'ANCILLARY_CONTROLS_TOTAL', val: 0 },
        { col: 'EYESIGHT_SERIOUS', val: 0 },
        { col: 'REV_LEFT_TRAIL_CONT_SERIOUS', val: 0 },
        { col: 'REV_LEFT_TRAIL_OBSERV_SERIOUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_SERIOUS', val: 0 },
        { col: 'PRECAUTIONS_SERIOUS', val: 0 },
        { col: 'CONTROL_ACC_SERIOUS', val: 0 },
        { col: 'CONTROL_CLUTCH_SERIOUS', val: 0 },
        { col: 'CONTROL_GEARS_SERIOUS', val: 0 },
        { col: 'CONTROL_FOOTBRAKE_SERIOUS', val: 0 },
        { col: 'CONTROL_PARK_SERIOUS', val: 0 },
        { col: 'CONTROL_STEERING_SERIOUS', val: 0 },
        { col: 'MOVE_OFF_SAFETY_SERIOUS', val: 0 },
        { col: 'MOVE_OFF_CONTROL_SERIOUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SIG_SERIOUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_DIR_SERIOUS', val: 0 },
        { col: 'MIRRORS_MC_REAR_SPE_SERIOUS', val: 0 },
        { col: 'SIGNALS_NECESSARY_SERIOUS', val: 0 },
        { col: 'SIGNALS_CORRECTLY_SERIOUS', val: 0 },
        { col: 'SIGNALS_TIMED_SERIOUS', val: 0 },
        { col: 'CLEARANCE_OBSTRUCT_SERIOUS', val: 0 },
        { col: 'RESPONSE_TRAF_SIGNS_SERIOUS', val: 0 },
        { col: 'RESPONSE_ROAD_MARK_SERIOUS', val: 0 },
        { col: 'RESPONSE_TRAF_LIGHT_SERIOUS', val: 0 },
        { col: 'RESPONSE_TRAF_CONT_SERIOUS', val: 0 },
        { col: 'RESPONSE_OTHER_SERIOUS', val: 0 },
        { col: 'USE_OF_SPEED_SERIOUS', val: 0 },
        { col: 'FOLLOWING_DISTANCE_SERIOUS', val: 0 },
        { col: 'MAINTAIN_PROG_SPEED_SERIOUS', val: 0 },
        { col: 'MAINTAIN_PROG_HES_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_SPEED_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_OBSERV_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_TURN_RIGHT_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_TURN_LEFT_SERIOUS', val: 0 },
        { col: 'JUNCTIONS_TURN_CUT_SERIOUS', val: 0 },
        { col: 'JUDGEMENT_OVER_SERIOUS', val: 0 },
        { col: 'JUDGEMENT_MEET_SERIOUS', val: 0 },
        { col: 'JUDGEMENT_CROSS_SERIOUS', val: 0 },
        { col: 'POSITIONING_NORMAL_SERIOUS', val: 0 },
        { col: 'POSITIONING_LANE_SERIOUS', val: 0 },
        { col: 'PEDESTRIAN_CROSSING_SERIOUS', val: 0 },
        { col: 'POSTITION_STOPS_SERIOUS', val: 0 },
        { col: 'AWARENESS_PLAN_SERIOUS', val: 0 },
        { col: 'ANCILLARY_CONTROLS_SERIOUS', val: 0 },
      //   { col: 'CONTROL_STOP_PROMPT_DANGEROUS', val: 0 },
      //   { col: 'REV_RIGHT_TRAIL_CONT_DANGER', val: 0 },
      //   { col: 'REV_RIGHT_TRAIL_OBSERV_DANGER', val: 0 },
      //   { col: 'REV_PARK_CPARK_CONTROL_DANGER', val: 0 },
      //   { col: 'REV_PARK_CPARK_OBSERVE_DANGER', val: 0 },
      //   { col: 'REV_PARK_ROAD_CONTROL_DANGER', val: 0 },
      //   { col: 'REV_PARK_ROAD_OBSERVE_DANGER', val: 0 },
        { col: 'VEHICLE_CHECKS_DANGEROUS', val: 0 },
        { col: 'UNCOUPLE_RECOUPLE_DANGEROUS', val: 1 },
        { col: 'PRECAUTIONS_DANGEROUS', val: 1 },
        { col: 'CONTROL_ACC_DANGEROUS', val: 1 },
        { col: 'CONTROL_CLUTCH_DANGEROUS', val: 1 },
        { col: 'CONTROL_GEARS_DANGEROUS', val: 1 },
        { col: 'CONTROL_FOOTBRAKE_DANGEROUS', val: 1 },
        { col: 'CONTROL_PARK_DANGEROUS', val: 1 },
        { col: 'CONTROL_STEERING_DANGEROUS', val: 1 },
        { col: 'MOVE_OFF_SAFETY_DANGEROUS', val: 1 },
        { col: 'MOVE_OFF_CONTROL_DANGEROUS', val: 1 },
        { col: 'MIRRORS_MC_REAR_SIG_DANGEROUS', val: 1 },
        { col: 'MIRRORS_MC_REAR_DIR_DANGEROUS', val: 1 },
        { col: 'MIRRORS_MC_REAR_SPE_DANGEROUS', val: 1 },
        { col: 'SIGNALS_NECESSARY_DANGEROUS', val: 1 },
        { col: 'SIGNALS_CORRECTLY_DANGEROUS', val: 1 },
        { col: 'SIGNALS_TIMED_DANGEROUS', val: 1 },
        { col: 'CLEARANCE_OBSTRUCT_DANGEROUS', val: 1 },
        { col: 'RESPONSE_TRAF_SIGNS_DANGEROUS', val: 1 },
        { col: 'RESPONSE_ROAD_MARK_DANGEROUS', val: 1 },
        { col: 'RESPONSE_TRAF_LIGHT_DANGEROUS', val: 1 },
        { col: 'RESPONSE_TRAF_CONT_DANGEROUS', val: 1 },
        { col: 'RESPONSE_OTHER_DANGEROUS', val: 1 },
        { col: 'USE_OF_SPEED_DANGEROUS', val: 1 },
        { col: 'FOLLOWING_DISTANCE_DANGEROUS', val: 1 },
        { col: 'MAINTAIN_PROG_SPEED_DANGEROUS', val: 1 },
        { col: 'MAINTAIN_PROG_HES_DANGEROUS', val: 1 },
        { col: 'JUNCTIONS_SPEED_DANGEROUS', val: 1 },
        { col: 'JUNCTIONS_OBSERV_DANGEROUS', val: 1 },
        { col: 'JUNCTIONS_TURN_RIGHT_DANGEROUS', val: 1 },
        { col: 'JUNCTIONS_TURN_LEFT_DANGEROUS', val: 1 },
        { col: 'JUNCTIONS_TURN_CUT_DANGEROUS', val: 1 },
        { col: 'JUDGEMENT_OVER_DANGEROUS', val: 1 },
        { col: 'JUDGEMENT_MEET_DANGEROUS', val: 1 },
        { col: 'JUDGEMENT_CROSS_DANGEROUS', val: 1 },
        { col: 'POSITIONING_NORMAL_DANGEROUS', val: 1 },
        { col: 'POSITIONING_LANE_DANGEROUS', val: 1 },
        { col: 'PEDESTRIAN_CROSSING_DANGEROUS', val: 1 },
        { col: 'POSTITION_STOPS_DANGEROUS', val: 1 },
        { col: 'AWARENESS_PLAN_DANGEROUS', val: 1 },
        { col: 'ANCILLARY_CONTROLS_DANGEROUS', val: 1 },
        { col: 'EYESIGHT_COMPLETED', val: 1 },
        { col: 'REV_LEFT_TRAIL_COMPLETED', val: 1 },
        { col: 'VEHICLE_CHECKS_COMPLETED', val: 1 },
        { col: 'NORMAL_STOP_1_COMPLETED', val: 1 },
        { col: 'NORMAL_STOP_2_COMPLETED', val: 1 },
        { col: 'ANGLED_START_COMPLETED', val: 1 },
        { col: 'UPHILL_START', val: 1 },
        { col: 'DOWN_HILL_START', val: 1 },
        { col: 'PRECAUTIONS_COMMENT', val: 'precautions dangerous' },
        { col: 'CONTROL_ACC_COMMENT', val: 'controls accelerator dangerous' },
        { col: 'CONTROL_CLUTCH_COMMENT', val: 'controls clutch dangerous' },
        { col: 'CONTROL_GEARS_COMMENT', val: 'controls gears dangerous' },
        { col: 'CONTROL_FOOTBRAKE_COMMENT', val: 'controls footbrake dangerous' },
        { col: 'CONTROL_PARK_COMMENT', val: 'controls parking brake dangerous' },
        { col: 'CONTROL_STEERING_COMMENT', val: 'controls steering dangerous' },
        { col: 'MOVE_OFF_SAFETY_COMMENT', val: 'move off safety dangerous' },
        { col: 'MOVE_OFF_CONTROL_COMMENT', val: 'move off control dangerous' },
        { col: 'MIRRORS_MC_REAR_SIG_COMMENT', val: 'use of mirrors signalling dangerous' },
        { col: 'MIRRORS_MC_REAR_DIR_COMMENT', val: 'use of mirrors change direction dangerous' },
        { col: 'MIRRORS_MC_REAR_SPE_COMMENT', val: 'use of mirrors change speed dangerous' },
        { col: 'SIGNALS_NECESSARY_COMMENT', val: 'signals necessary dangerous' },
        { col: 'SIGNALS_CORRECTLY_COMMENT', val: 'signals correctly dangerous' },
        { col: 'SIGNALS_TIMED_COMMENT', val: 'signals timed dangerous' },
        { col: 'CLEARANCE_OBSTRUCT_COMMENT', val: 'clearance dangerous' },
        { col: 'RESPONSE_TRAF_SIGNS_COMMENT', val: 'response to signs traffic signs dangerous' },
        { col: 'RESPONSE_ROAD_MARK_COMMENT', val: 'response to signs road markings dangerous' },
        { col: 'RESPONSE_TRAF_LIGHT_COMMENT', val: 'response to signs traffic lights dangerous' },
        { col: 'RESPONSE_TRAF_CONT_COMMENT', val: 'response to signs traffic controllers dangerous' },
        { col: 'RESPONSE_OTHER_COMMENT', val: 'response to signs other road users dangerous' },
        { col: 'USE_OF_SPEED_COMMENT', val: 'use of speed dangerous' },
        { col: 'FOLLOWING_DISTANCE_COMMENT', val: 'following distance dangerous' },
        { col: 'MAINTAIN_PROG_SPEED_COMMENT', val: 'progress appropriate speed dangerous' },
        { col: 'MAINTAIN_PROG_HES_COMMENT', val: 'progress undue hesitation dangerous' },
        { col: 'JUNCTIONS_SPEED_COMMENT', val: 'junctions approach speed dangerous' },
        { col: 'JUNCTIONS_OBSERV_COMMENT', val: 'junctions observation dangerous' },
        { col: 'JUNCTIONS_TURN_RIGHT_COMMENT', val: 'junctions turning right dangerous' },
        { col: 'JUNCTIONS_TURN_LEFT_COMMENT', val: 'junctions turning left dangerous' },
        { col: 'JUNCTIONS_TURN_CUT_COMMENT', val: 'junctions cutting corners dangerous' },
        { col: 'JUDGEMENT_OVER_COMMENT', val: 'judgement overtaking dangerous' },
        { col: 'JUDGEMENT_MEET_COMMENT', val: 'judgement meeting dangerous' },
        { col: 'JUDGEMENT_CROSS_COMMENT', val: 'judgement crossing dangerous' },
        { col: 'POSITIONING_NORMAL_COMMENT', val: 'positioning normal driving dangerous' },
        { col: 'POSITIONING_LANE_COMMENT', val: 'positioning lane discipline dangerous' },
        { col: 'PEDESTRIAN_CROSSING_COMMENT', val: 'pedestrian crossings dangerous' },
        { col: 'POSITION_STOPS_COMMENT', val: 'position normal stops dangerous' },
        { col: 'AWARENESS_PLAN_COMMENT', val: 'awareness planning dangerous' },
        { col: 'ANCILLARY_CONTROLS_COMMENT', val: 'ancillary controls dangerous' },
      //   { col: 'SHOW_ME_1_CODE', val: 'S2' },
      //   { col: 'SHOW_ME_1_DESCRIPTION', val: 'Second Show Me Question' },
      //   { col: 'TELL_ME_1_CODE', val: 'T1' },
      //   { col: 'TELL_ME_1_DESCRIPTION', val: 'First Tell Me Question' },
        { col: 'INDEPENDENT_DRIVING', val: 'N/A' },
    ];

    // expect all dangerous, no faults or serious
    expect(mapCatBEData(fullyPopulated)).toEqual(expected);
  });
});
